import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import axios from 'axios'
import { refreshAuth } from '../lib/auth.js'

const Icon = ({ name, size = 20 }) => { const p = { user:<><circle cx="12" cy="8" r="4"/><path d="M4 21c.7-4 3.4-6 8-6s7.3 2 8 6"/></>, save:<><path d="M5 4h14v16H5z"/><path d="M8 4v5h8V4M8 20v-5h8v5"/></>, camera:<><path d="M4 7h4l1.5-2h5L16 7h4v12H4z"/><circle cx="12" cy="13" r="3"/></>, arrow:<><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></> }; return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg> }
const avatarFallback = name => `https://ui-avatars.com/api/?name=${encodeURIComponent(name || 'BinerCraft')}&background=2563eb&color=fff&size=240`

export default function AccountSettingsPage() {
  const [user, setUser] = useState(null); const [form, setForm] = useState({ username:'', displayName:'', email:'', password:'', avatar:'' }); const [busy,setBusy] = useState(false); const [msg,setMsg] = useState({type:'',text:''}); const navigate=useNavigate()
  useEffect(() => { let alive=true; refreshAuth().then(u => { if(!alive)return; if(!u){navigate('/login',{replace:true});return} setUser(u); setForm({username:u.username||'',displayName:u.displayName||'',email:u.email||'',password:'',avatar:u.avatar||''}) }); return()=>{alive=false} },[navigate])
  const update=(key,value)=>setForm(f=>({...f,[key]:value}))
  const chooseAvatar=e=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return setMsg({type:'error',text:'فقط فایل تصویری انتخاب کنید.'});if(file.size>500*1024)return setMsg({type:'error',text:'حجم آواتار باید کمتر از ۵۰۰ کیلوبایت باشد.'});const reader=new FileReader();reader.onload=()=>update('avatar',String(reader.result||''));reader.readAsDataURL(file)}
  const save=async e=>{e.preventDefault();if(!user?.token)return;setBusy(true);setMsg({type:'',text:''});try{const payload={username:form.username,displayName:form.displayName,email:form.email,avatar:form.avatar};if(form.password)payload.password=form.password;const r=await axios.patch('/api/account',payload,{headers:{Authorization:`Bearer ${user.token}`}});const next={...user,...r.data,token:user.token};localStorage.setItem('user',JSON.stringify(next));localStorage.setItem('binercraft_user_token',user.token);setUser(next);setForm(f=>({...f,password:''}));setMsg({type:'ok',text:'اطلاعات حساب با موفقیت ذخیره شد.'})}catch(err){setMsg({type:'error',text:err.response?.data?.error||'ذخیره اطلاعات انجام نشد.'})}finally{setBusy(false)}}
  if(!user)return <main className="container mx-auto max-w-4xl px-4 py-14"><div className="h-96 animate-pulse rounded-3xl border border-glass-border bg-glass-bg/50"/></main>
  return <main className="container mx-auto max-w-4xl px-4 py-10 sm:py-14"><div className="mb-6"><Link to="/profile" className="inline-flex items-center gap-2 text-sm font-bold text-primary-600 dark:text-primary-400"><Icon name="arrow" size={17}/> بازگشت به پروفایل</Link></div><section className="overflow-hidden rounded-[2rem] border border-glass-border bg-glass-bg/50 shadow-xl"><header className="border-b border-glass-border bg-gradient-to-br from-primary-600/15 via-background to-purple-600/10 p-6 sm:p-8"><div className="flex items-center gap-4"><span className="rounded-2xl bg-primary-500/10 p-3 text-primary-500"><Icon name="user" size={28}/></span><div><h1 className="text-2xl font-black sm:text-3xl">تنظیمات حساب</h1><p className="mt-1 text-text-secondary">مدیریت اطلاعات حساب، ایمیل، رمز عبور و آواتار.</p></div></div></header><form onSubmit={save} className="space-y-6 p-6 sm:p-8"><div className="flex flex-col items-center gap-4 sm:flex-row"><img src={form.avatar||avatarFallback(form.displayName||form.username)} alt="آواتار" className="h-28 w-28 rounded-3xl border-4 border-background object-cover shadow-lg" onError={e=>{e.currentTarget.src=avatarFallback(form.displayName||form.username)}}/><div><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-glass-border bg-glass-bg px-4 py-3 font-bold transition hover:border-primary-500/40"><Icon name="camera" size={18}/> انتخاب آواتار<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" className="hidden" onChange={chooseAvatar}/></label><p className="mt-2 text-xs text-text-secondary">PNG، JPG، WEBP یا GIF · حداکثر ۵۰۰KB</p></div></div><div className="grid gap-5 md:grid-cols-2">{[['displayName','نام نمایشی','text'],['username','نام کاربری','text'],['email','ایمیل','email'],['password','رمز عبور جدید (اختیاری)','password']].map(([key,label,type])=><label key={key} className="block"><span className="mb-2 block text-sm font-bold">{label}</span><input type={type} value={form[key]} onChange={e=>update(key,e.target.value)} className="w-full rounded-2xl border border-glass-border bg-background/70 px-4 py-3 outline-none transition focus:border-primary-500" autoComplete={key==='password'?'new-password':'off'}/></label>)}</div>{msg.text&&<div className={`rounded-2xl border p-4 text-sm font-bold ${msg.type==='ok'?'border-emerald-500/20 bg-emerald-500/10 text-emerald-600':'border-red-500/20 bg-red-500/10 text-red-500'}`}>{msg.text}</div>}<button disabled={busy} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-primary-600 px-5 py-4 font-black text-white shadow-lg shadow-primary-600/20 disabled:cursor-not-allowed disabled:opacity-60"><Icon name="save" size={19}/>{busy?'در حال ذخیره...':'ذخیره تغییرات'}</button></form></section></main>
}
