import { useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { Navigate } from 'react-router-dom'

const API = '/api'
const TOKEN_KEY = 'binercraft_admin_token'
const USER_KEY = 'binercraft_user'
const Icon = ({ name, size = 20 }) => { const p = { grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>, users:<><path d="M16 20v-1.5a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4V20"/><circle cx="9.5" cy="7" r="3.5"/><path d="M17 11a3.5 3.5 0 0 0-1.5-6.6"/></>, box:<><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9Z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></>, article:<><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></>, ticket:<><path d="M4 7h16v4a2 2 0 0 0 0 4v4H4v-4a2 2 0 0 0 0-4Z"/><path d="M12 7v2M12 15v2"/></>, tag:<><path d="M20 13 13 20 4 11V4h7l9 9Z"/><path d="M8 8h.01"/></>, settings:<><path d="M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z"/><path d="m19.4 15 .1.1-1.8 3.1-.1-.1a3 3 0 0 1-3.2.5h-.1a3 3 0 0 1-2.3 1.1h-.2a3 3 0 0 1-2.3-1.1h-.1a3 3 0 0 1-3.2-.5l-.1.1-1.8-3.1.1-.1a3 3 0 0 1 0-3.6l-.1-.1 1.8-3.1.1.1a3 3 0 0 1 3.2-.5h.1A3 3 0 0 1 12 6.7h.2a3 3 0 0 1 2.3 1.1h.1a3 3 0 0 1 3.2.5l.1-.1 1.8 3.1-.1.1a3 3 0 0 1 0 3.6Z"/></>, logout:<><path d="M10 17l5-5-5-5M15 12H3"/><path d="M21 19V5a2 2 0 0 0-2-2h-6"/></>, plus:<><path d="M12 5v14M5 12h14"/></>, trash:<><path d="M4 7h16M10 11v6M14 11v6M6 7l1 13h10l1-13M9 7V4h6v3"/></>, edit:<><path d="m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10Z"/><path d="m14.5 7.5 2 2"/></> }; return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg> }

async function api(path, options = {}) { const token = localStorage.getItem(TOKEN_KEY); const r = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type':'application/json', ...(token ? { Authorization:`Bearer ${token}` } : {}), ...(options.headers || {}) } }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || 'خطایی رخ داد'); return data }
const blankPost = { title:'', summary:'', content:'', category:'اخبار', image:'', published:true }
const blankProduct = { name:'', category:'رتبه‌ها', price:'', description:'', image:'' }
const blankDiscount = { code:'', description:'', discount:10, type:'percent', maxUses:100, active:true, expiryDate:'2099-12-31' }
const input = 'w-full rounded-xl border border-border bg-background px-4 py-3 outline-none focus:border-primary-500'

export default function AdminPanel() {
  const [token,setToken]=useState(()=>localStorage.getItem(TOKEN_KEY)); const [login,setLogin]=useState({username:'hirad990',password:''}); const [loginError,setLoginError]=useState(''); const [active,setActive]=useState('overview'); const [overview,setOverview]=useState(null); const [users,setUsers]=useState([]); const [products,setProducts]=useState([]); const [posts,setPosts]=useState([]); const [orders,setOrders]=useState([]); const [tickets,setTickets]=useState([]); const [discounts,setDiscounts]=useState([]); const [settings,setSettings]=useState({}); const [stats,setStats]=useState({}); const [post,setPost]=useState(blankPost); const [product,setProduct]=useState(blankProduct); const [discount,setDiscount]=useState(blankDiscount); const [editingPost,setEditingPost]=useState(null); const [editingProduct,setEditingProduct]=useState(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const adminUser=useMemo(()=>{try{return JSON.parse(localStorage.getItem(USER_KEY)||'null')}catch{return null}},[token])
  const load=async()=>{try{setError(''); const [o,u,p,b,ord,t,d,s,ss]=await Promise.all([api('/admin/overview'),api('/users'),api('/products'),api('/blog'),api('/orders'),api('/tickets'),api('/discounts'),api('/site-settings'),api('/server-stats')]); setOverview(o);setUsers(u);setProducts(p);setPosts(b);setOrders(ord);setTickets(t);setDiscounts(d);setSettings(s);setStats(ss)}catch(e){if(['Authentication required','Admin access required'].includes(e.message)) logout();else setError(e.message)}}
  useEffect(()=>{if(token)load()},[token])
  async function handleLogin(e){e.preventDefault();setBusy(true);setLoginError('');try{const data=await fetch(`${API}/auth/admin/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);return b});localStorage.setItem(TOKEN_KEY,data.token);localStorage.setItem(USER_KEY,JSON.stringify(data.user));setToken(data.token)}catch(e){setLoginError(e.message)}finally{setBusy(false)}}
  function logout(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);setToken(null)}
  async function savePost(e){e.preventDefault();setBusy(true);try{if(editingPost)await api(`/blog/${editingPost}`,{method:'PATCH',body:JSON.stringify(post)});else await api('/blog',{method:'POST',body:JSON.stringify(post)});setPost(blankPost);setEditingPost(null);await load();setActive('blog')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function saveProduct(e){e.preventDefault();setBusy(true);try{const body={...product,price:Number(product.price)};if(editingProduct)await api(`/products/${editingProduct}`,{method:'PATCH',body:JSON.stringify(body)});else await api('/products',{method:'POST',body:JSON.stringify(body)});setProduct(blankProduct);setEditingProduct(null);await load();setActive('products')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function saveDiscount(e){e.preventDefault();setBusy(true);try{await api('/discounts',{method:'POST',body:JSON.stringify({...discount,discount:Number(discount.discount),maxUses:Number(discount.maxUses)})});setDiscount(blankDiscount);await load();setActive('discounts')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function patchUser(id,body){try{await api(`/users/${id}`,{method:'PATCH',body:JSON.stringify(body)});await load()}catch(e){setError(e.message)}}
  async function remove(path){if(!window.confirm('این مورد حذف شود؟'))return;try{await api(path,{method:'DELETE'});await load()}catch(e){setError(e.message)}}
  async function saveSettings(e){e.preventDefault();try{await api('/site-settings',{method:'PATCH',body:JSON.stringify(settings)});await load()}catch(e){setError(e.message)}}
  async function saveStats(e){e.preventDefault();try{await api('/server-stats',{method:'PATCH',body:JSON.stringify({...stats,players:Number(stats.players),stability:Number(stats.stability),sales:Number(stats.sales),support:Number(stats.support)})});await load()}catch(e){setError(e.message)}}
  if(!token)return <div className="min-h-[70vh] flex items-center justify-center px-4 py-10"><motion.form onSubmit={handleLogin} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="glass-card w-full max-w-md p-7"><div className="mb-7"><div className="mb-4 inline-flex items-center gap-2 rounded-2xl bg-primary-500/10 px-3 py-2 text-sm font-bold text-primary-500"><Icon name="settings"/> BinerCraft Admin</div><h1 className="text-3xl font-black">ورود مدیریت</h1><p className="mt-2 text-text-secondary">مدیریت کامل فروشگاه و محتوای سایت</p></div>{loginError&&<div className="mb-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-500">{loginError}</div>}<label className="mb-2 block text-sm font-bold">نام کاربری</label><input className={`${input} mb-4`} value={login.username} onChange={e=>setLogin({...login,username:e.target.value})}/><label className="mb-2 block text-sm font-bold">رمز عبور</label><input required type="password" className={`${input} mb-6`} value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button disabled={busy} className="w-full rounded-xl bg-primary-600 px-4 py-3 font-black text-white disabled:opacity-60">{busy?'در حال ورود...':'ورود به پنل'}</button></motion.form></div>
  if(adminUser?.role!=='admin')return <Navigate to="/" replace/>
  const nav=[['overview','داشبورد','grid'],['users','کاربران','users'],['products','محصولات','box'],['blog','وبلاگ','article'],['orders','سفارش‌ها','box'],['tickets','تیکت‌ها','ticket'],['discounts','تخفیف‌ها','tag'],['settings','تنظیمات سایت','settings']]
  const cards=overview?[['کاربران',overview.users,'users'],['محصولات',overview.products,'box'],['مطالب',overview.posts,'article'],['سفارش‌ها',overview.orders,'box'],['تیکت باز',overview.openTickets,'ticket'],['درآمد',`${Number(overview.revenue||0).toLocaleString('fa-IR')} تومان`,'tag']]:[]
  return <main className="container mx-auto max-w-7xl px-4 py-8"><div className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-1 flex items-center gap-2 text-sm font-bold text-primary-500"><Icon name="settings" size={16}/> CONTROL CENTER</div><h1 className="text-3xl font-black sm:text-4xl">پنل مدیریت BinerCraft</h1><p className="mt-2 text-text-secondary">مدیریت یکپارچه فروشگاه، محتوا و کاربران</p></div><button onClick={logout} className="inline-flex items-center justify-center gap-2 rounded-xl border border-border px-4 py-2.5 font-bold"><Icon name="logout"/> خروج امن</button></div>{error&&<div className="mb-5 rounded-xl bg-red-500/10 p-3 text-sm text-red-500">{error}</div>}<div className="mb-7 grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-6">{cards.map(([label,value,icon])=><div key={label} className="glass-card p-5"><Icon name={icon} size={23}/><div className="mt-3 text-2xl font-black">{value}</div><div className="mt-1 text-sm text-text-secondary">{label}</div></div>)}</div><div className="grid gap-6 lg:grid-cols-[210px_1fr]"><aside className="glass-card h-fit p-3">{nav.map(([id,label,icon])=><button key={id} onClick={()=>setActive(id)} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-right text-sm font-bold transition ${active===id?'bg-primary-500 text-white':'hover:bg-black/5 dark:hover:bg-white/5'}`}><Icon name={icon} size={18}/>{label}</button>)}</aside><section className="glass-card min-w-0 p-5 sm:p-7">
    {active==='overview'&&overview&&<div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-border p-5"><h2 className="mb-4 text-xl font-black">وضعیت سرور</h2>{[['status','وضعیت'],['players','بازیکنان'],['stability','پایداری']].map(([k,l])=><div key={k} className="flex justify-between border-b border-border/50 py-3"><span>{l}</span><b>{overview.serverStats?.[k] ?? '—'}{k==='stability'?'%':''}</b></div>)}</div><div className="rounded-2xl border border-border p-5"><h2 className="mb-4 text-xl font-black">دسترسی سریع</h2><div className="grid gap-3 sm:grid-cols-2">{[['blog','مدیریت وبلاگ'],['products','مدیریت محصولات'],['users','مدیریت کاربران'],['settings','تنظیمات سایت']].map(([id,l])=><button key={id} onClick={()=>setActive(id)} className="rounded-xl border border-border p-4 text-right font-bold hover:border-primary-500/40">{l}</button>)}</div></div></div>}
    {active==='users'&&<div><h2 className="mb-5 text-xl font-black">مدیریت کاربران و Role</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-right"><th className="p-3">کاربر</th><th className="p-3">ایمیل</th><th className="p-3">نقش</th><th className="p-3">کیف پول</th><th className="p-3">عملیات</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-border/50"><td className="p-3 font-bold">{u.displayName||u.username}</td><td className="p-3">{u.email||'—'}</td><td className="p-3"><select value={u.role||'user'} onChange={e=>patchUser(u.id,{role:e.target.value})} className="rounded-lg border border-border bg-background px-2 py-1"><option value="user">user</option><option value="admin">admin</option></select></td><td className="p-3">{Number(u.wallet||0).toLocaleString('fa-IR')}</td><td className="p-3"><button onClick={()=>remove(`/users/${u.id}`)} className="text-red-500"><Icon name="trash"/></button></td></tr>)}</tbody></table></div></div>}
    {active==='products'&&<div><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black">مدیریت محصولات</h2><button onClick={()=>{setProduct(blankProduct);setEditingProduct(null);setActive('product-form')}} className="inline-flex items-center gap-2 rounded-xl bg-primary-600 px-4 py-2.5 font-bold text-white"><Icon name="plus"/> محصول</button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{products.map(p=><div key={p.id} className="rounded-2xl border border-border p-5"><h3 className="font-black">{p.name}</h3><p className="mt-1 text-sm text-text-secondary">{p.category}</p><b className="mt-4 block text-primary-500">{Number(p.price||0).toLocaleString('fa-IR')} تومان</b><div className="mt-4 flex gap-2"><button onClick={()=>{setProduct({...p});setEditingProduct(p.id);setActive('product-form')}} className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-2"><Icon name="edit" size={16}/> ویرایش</button><button onClick={()=>remove(`/products/${p.id}`)} className="rounded-lg border border-red-500/20 px-3 py-2 text-red-500"><Icon name="trash" size={16}/></button></div></div>)}</div></div>}
    {active==='product-form'&&<form onSubmit={saveProduct} className="max-w-2xl"><h2 className="mb-5 text-xl font-black">{editingProduct?'ویرایش محصول':'محصول جدید'}</h2><div className="grid gap-4 sm:grid-cols-2">{[['name','نام محصول'],['category','دسته‌بندی'],['price','قیمت'],['image','تصویر']].map(([k,l])=><div key={k}><label className="mb-2 block text-sm font-bold">{l}</label><input required={k!=='image'} type={k==='price'?'number':'text'} className={input} value={product[k]??''} onChange={e=>setProduct({...product,[k]:e.target.value})}/></div>)}</div><label className="mb-2 mt-4 block text-sm font-bold">توضیحات</label><textarea rows="5" className={input} value={product.description} onChange={e=>setProduct({...product,description:e.target.value})}/><button className="mt-5 rounded-xl bg-primary-600 px-5 py-3 font-black text-white">ذخیره محصول</button></form>}
    {active==='blog'&&<div><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black">مدیریت کامل وبلاگ</h2><button onClick={()=>{setPost(blankPost);setEditingPost(null);setActive('blog-form')}} className="inline-flex items-center gap-2 rounded-xl bg-primary-600 px-4 py-2.5 font-bold text-white"><Icon name="plus"/> مطلب جدید</button></div><div className="space-y-3">{posts.map(p=><div key={p.id} className="flex flex-col gap-3 rounded-2xl border border-border p-4 md:flex-row md:items-center md:justify-between"><div><h3 className="font-black">{p.title}</h3><p className="mt-1 text-sm text-text-secondary">{p.category} · {p.date} · {p.published===false?'پیش‌نویس':'منتشر شده'}</p></div><div className="flex gap-2"><button onClick={()=>{setPost({...p});setEditingPost(p.id);setActive('blog-form')}} className="inline-flex items-center gap-1 rounded-lg border border-border px-3 py-2"><Icon name="edit" size={16}/> ویرایش</button><button onClick={()=>remove(`/blog/${p.id}`)} className="rounded-lg border border-red-500/20 px-3 py-2 text-red-500"><Icon name="trash" size={16}/></button></div></div>)}</div></div>}
    {active==='blog-form'&&<form onSubmit={savePost}><h2 className="mb-5 text-xl font-black">{editingPost?'ویرایش مطلب':'انتشار مطلب جدید'}</h2><div className="grid gap-4 sm:grid-cols-2"><input required placeholder="عنوان" className={input} value={post.title} onChange={e=>setPost({...post,title:e.target.value})}/><input placeholder="دسته‌بندی" className={input} value={post.category} onChange={e=>setPost({...post,category:e.target.value})}/><input placeholder="خلاصه" className={input} value={post.summary} onChange={e=>setPost({...post,summary:e.target.value})}/><input placeholder="URL تصویر" className={input} value={post.image} onChange={e=>setPost({...post,image:e.target.value})}/></div><textarea required rows="15" placeholder="محتوا با Markdown" className={`${input} mt-4`} value={post.content} onChange={e=>setPost({...post,content:e.target.value})}/><label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={post.published!==false} onChange={e=>setPost({...post,published:e.target.checked})}/> انتشار عمومی</label><button className="mt-5 rounded-xl bg-primary-600 px-5 py-3 font-black text-white">ذخیره مطلب</button></form>}
    {active==='orders'&&<div><h2 className="mb-5 text-xl font-black">سفارش‌ها</h2><div className="space-y-3">{orders.length?orders.map(o=><div key={o.id} className="flex flex-col gap-2 rounded-2xl border border-border p-4 md:flex-row md:items-center md:justify-between"><div><b>#{String(o.id).slice(-8)}</b><p className="text-sm text-text-secondary">کاربر: {o.userId}</p></div><b>{Number(o.total||o.amount||0).toLocaleString('fa-IR')} تومان</b><select value={o.status||'pending'} onChange={e=>api(`/orders/${o.id}`,{method:'PATCH',body:JSON.stringify({status:e.target.value})}).then(load).catch(x=>setError(x.message))} className="rounded-lg border border-border bg-background px-3 py-2"><option>pending</option><option>processing</option><option>completed</option><option>cancelled</option></select></div>):<p className="text-text-secondary">هنوز سفارشی ثبت نشده.</p>}</div></div>}
    {active==='tickets'&&<div><h2 className="mb-5 text-xl font-black">تیکت‌های پشتیبانی</h2><div className="space-y-3">{tickets.length?tickets.map(t=><div key={t.id} className="rounded-2xl border border-border p-4"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><b>{t.subject||'بدون عنوان'}</b><p className="text-sm text-text-secondary">کاربر: {t.userId}</p></div><select value={t.status||'open'} onChange={e=>api(`/tickets/${t.id}`,{method:'PATCH',body:JSON.stringify({status:e.target.value})}).then(load).catch(x=>setError(x.message))} className="rounded-lg border border-border bg-background px-3 py-2"><option>open</option><option>pending</option><option>resolved</option><option>closed</option></select></div></div>):<p className="text-text-secondary">تیکتی وجود ندارد.</p>}</div></div>}
    {active==='discounts'&&<div><h2 className="mb-5 text-xl font-black">مدیریت کدهای تخفیف</h2><form onSubmit={saveDiscount} className="mb-7 grid gap-3 rounded-2xl border border-border p-4 md:grid-cols-5"><input required placeholder="CODE" className={input} value={discount.code} onChange={e=>setDiscount({...discount,code:e.target.value.toUpperCase()})}/><input placeholder="توضیح" className={input} value={discount.description} onChange={e=>setDiscount({...discount,description:e.target.value})}/><input type="number" min="0" className={input} value={discount.discount} onChange={e=>setDiscount({...discount,discount:e.target.value})}/><select className={input} value={discount.type} onChange={e=>setDiscount({...discount,type:e.target.value})}><option value="percent">درصدی</option><option value="fixed">مبلغ ثابت</option></select><button className="rounded-xl bg-primary-600 px-4 py-3 font-black text-white">افزودن</button></form><div className="space-y-3">{discounts.map(d=><div key={d.id} className="flex items-center justify-between rounded-2xl border border-border p-4"><div><b>{d.code}</b><p className="text-sm text-text-secondary">{d.discount}{d.type==='percent'?'%':' تومان'} · {d.active===false?'غیرفعال':'فعال'}</p></div><button onClick={()=>remove(`/discounts/${d.id}`)} className="text-red-500"><Icon name="trash"/></button></div>)}</div></div>}
    {active==='settings'&&<div className="grid gap-6 xl:grid-cols-2"><form onSubmit={saveSettings} className="rounded-2xl border border-border p-5"><h2 className="mb-5 flex items-center gap-2 text-xl font-black"><Icon name="settings"/> تنظیمات سایت</h2>{[['siteName','نام سایت'],['supportEmail','ایمیل پشتیبانی'],['supportHours','ساعات پاسخ‌گویی'],['serverAddress','آدرس سرور'],['announcement','اعلان سراسری'],['contactText','متن تماس با ما']].map(([k,l])=><div key={k} className="mb-4"><label className="mb-2 block text-sm font-bold">{l}</label><input className={input} value={settings[k]||''} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></div>)}<button className="rounded-xl bg-primary-600 px-5 py-3 font-black text-white">ذخیره تنظیمات</button></form><form onSubmit={saveStats} className="rounded-2xl border border-border p-5"><h2 className="mb-5 text-xl font-black">آمار و وضعیت سرور</h2>{[['players','بازیکنان'],['stability','پایداری'],['sales','فروش'],['support','پشتیبانی']].map(([k,l])=><div key={k} className="mb-4"><label className="mb-2 block text-sm font-bold">{l}</label><input type="number" className={input} value={stats[k]??''} onChange={e=>setStats({...stats,[k]:e.target.value})}/></div>)}<label className="mb-2 block text-sm font-bold">وضعیت</label><select className={`${input} mb-4`} value={stats.status||'online'} onChange={e=>setStats({...stats,status:e.target.value})}><option value="online">online</option><option value="maintenance">maintenance</option><option value="offline">offline</option></select><button className="rounded-xl bg-primary-600 px-5 py-3 font-black text-white">ذخیره وضعیت</button></form></div>}
  </section></div></main>
}
