import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { motion, useReducedMotion } from 'framer-motion'
import { refreshAuth } from '../lib/auth.js'

const Icon = ({ name, size = 20 }) => { const p = { bell:<><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>, check:<path d="m5 12 4 4L19 6"/>, arrow:<><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></> }; return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg> }

export default function NotificationsPage() {
  const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [authLoading,setAuthLoading]=useState(true); const navigate=useNavigate(); const reduce=useReducedMotion()
  useEffect(()=>{let alive=true;refreshAuth().then(async user=>{if(!alive)return;if(!user){navigate('/login',{replace:true});return}try{const r=await fetch('/api/notifications',{headers:{Authorization:`Bearer ${user.token}`}});const data=await r.json().catch(()=>[]);if(!r.ok)throw new Error(data.error||'دریافت اعلان‌ها انجام نشد');setItems(Array.isArray(data)?data:[])}catch{setItems([])}finally{if(alive){setLoading(false);setAuthLoading(false)}}});return()=>{alive=false}},[navigate])
  const markRead=async id=>{const user=await refreshAuth();if(!user?.token)return;try{const r=await fetch(`/api/notifications/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${user.token}`},body:JSON.stringify({read:true})});if(r.ok)setItems(x=>x.map(n=>n.id===id?{...n,read:true}:n))}catch{}}
  if(authLoading)return <main className="container mx-auto max-w-4xl px-4 py-14"><div className="h-72 animate-pulse rounded-3xl border border-glass-border bg-glass-bg/50"/></main>
  return <main className="container mx-auto max-w-4xl px-4 py-10 sm:py-14"><Link to="/profile" className="inline-flex items-center gap-2 text-sm font-bold text-primary-600 dark:text-primary-400"><Icon name="arrow" size={17}/> پروفایل</Link><motion.div initial={reduce?false:{opacity:0,y:18}} animate={{opacity:1,y:0}} className="mt-5"><h1 className="text-3xl font-black">اعلان‌ها</h1><p className="mt-2 text-text-secondary">پیام‌ها و اطلاعیه‌های مرتبط با حساب شما.</p></motion.div>{loading?<div className="mt-7 h-64 animate-pulse rounded-3xl border border-glass-border bg-glass-bg/50"/>:items.length?<div className="mt-7 space-y-3">{items.map(n=><motion.article layout initial={reduce?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} key={n.id} className={`rounded-3xl border p-5 transition ${n.read?'border-glass-border bg-glass-bg/40':'border-primary-500/30 bg-primary-500/5'}`}><div className="flex gap-4"><span className="h-fit rounded-2xl bg-primary-500/10 p-3 text-primary-500"><Icon name="bell"/></span><div className="min-w-0 flex-1"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-black">{n.title||'اعلان BinerCraft'}</h2>{!n.read&&<button onClick={()=>markRead(n.id)} className="inline-flex w-fit items-center gap-1 rounded-lg px-2 py-1 text-xs font-bold text-primary-600"><Icon name="check" size={14}/> خواندم</button>}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-text-secondary">{n.message||n.content||''}</p><p className="mt-3 text-xs text-text-secondary">{n.createdAt?new Date(n.createdAt).toLocaleString('fa-IR'):'—'}</p></div></div></motion.article>)}</div>:<div className="mt-7 rounded-3xl border border-dashed border-glass-border p-12 text-center"><Icon name="bell" size={42}/><p className="mt-4 font-bold">اعلان جدیدی ندارید.</p></div>}</main>
}
