import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { motion, useReducedMotion } from 'framer-motion'
import { getToken, refreshAuth } from '../lib/auth.js'

const Icon = ({ name, size = 22 }) => { const p = { wallet:<><rect x="3" y="6" width="18" height="14" rx="2"/><path d="M16 10h5v5h-5a2.5 2.5 0 0 1 0-5Z"/><path d="M6 3h11a2 2 0 0 1 2 2"/></>,arrow:<><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></> }; return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg> }

export default function WalletPage() {
  const [user, setUser] = useState(null); const [wallet, setWallet] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const navigate = useNavigate(); const reduce = useReducedMotion()
  useEffect(() => { let alive = true; (async () => { const current = await refreshAuth(); if (!alive) return; if (!current) { navigate('/login', { replace: true }); return } setUser(current); try { const response = await fetch(`/api/wallet/${encodeURIComponent(current.id)}`, { headers: { Authorization: `Bearer ${getToken()}` } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'دریافت کیف پول انجام نشد'); const value = data.wallet ?? data.balance ?? current.wallet ?? 0; setWallet(Number(value) || 0) } catch (err) { if (alive) { setWallet(Number(current.wallet) || 0); setError(err.message) } } finally { if (alive) setLoading(false) } })(); return () => { alive = false } }, [navigate])
  if (!user) return <main className="container mx-auto max-w-4xl px-4 py-14"><div className="h-72 animate-pulse rounded-3xl border border-glass-border bg-glass-bg/50"/></main>
  return <main className="container mx-auto max-w-4xl px-4 py-10 sm:py-14"><Link to="/profile" className="inline-flex items-center gap-2 text-sm font-bold text-primary-600 dark:text-primary-400"><Icon name="arrow" size={17}/> پروفایل</Link><motion.section initial={reduce ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="mt-6 overflow-hidden rounded-[2rem] border border-glass-border bg-gradient-to-br from-primary-600/15 via-background to-purple-600/10 p-8 shadow-xl"><div className="flex items-center gap-4"><span className="rounded-2xl bg-primary-500/10 p-4 text-primary-500"><Icon name="wallet" size={30}/></span><div><h1 className="text-3xl font-black">کیف پول</h1><p className="mt-1 text-text-secondary">موجودی کیف پول حساب شما</p></div></div>{error && <div className="mt-6 rounded-2xl border border-amber-500/20 bg-amber-500/10 p-4 text-sm font-bold text-amber-600">{error}</div>}<div className="mt-8 rounded-3xl border border-glass-border bg-background/50 p-7 text-center"><p className="text-sm text-text-secondary">موجودی فعلی</p><p className="mt-3 text-4xl font-black text-primary-600 dark:text-primary-400">{loading ? '—' : wallet.toLocaleString('fa-IR')} تومان</p></div></motion.section></main>
}
