import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { getToken } from '../lib/auth.js'

export default function NotificationBell() {
  const [isOpen, setIsOpen] = useState(false); const [notifications, setNotifications] = useState([]); const [unreadCount, setUnreadCount] = useState(0); const containerRef = useRef(null); const shouldReduceMotion = useReducedMotion()
  const fetchNotifications = async () => { const token = getToken(); if (!token) { setNotifications([]); setUnreadCount(0); return } try { const response = await fetch('/api/notifications', { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) return; const items = await response.json(); const list = Array.isArray(items) ? items : []; setNotifications(list); setUnreadCount(list.filter(n => !n.read).length) } catch {} }
  useEffect(() => { fetchNotifications(); const interval = window.setInterval(fetchNotifications, 30000); return () => window.clearInterval(interval) }, [])
  useEffect(() => { if (!isOpen) return undefined; const pointer = e => { if (!containerRef.current?.contains(e.target)) setIsOpen(false) }; const key = e => { if (e.key === 'Escape') setIsOpen(false) }; document.addEventListener('mousedown', pointer); document.addEventListener('keydown', key); return () => { document.removeEventListener('mousedown', pointer); document.removeEventListener('keydown', key) } }, [isOpen])
  const markAsRead = async id => { const token=getToken(); if(!token)return; try { await fetch(`/api/notifications/${encodeURIComponent(id)}`, { method:'PATCH', headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}, body:JSON.stringify({read:true}) }); await fetchNotifications() } catch {} }
  const markAllAsRead = async () => { const token=getToken(); if(!token)return; try { await Promise.all(notifications.filter(n=>!n.read).map(n=>fetch(`/api/notifications/${encodeURIComponent(n.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({read:true})}))); await fetchNotifications() } catch {} }
  return <div ref={containerRef} className="relative"><button type="button" onClick={()=>setIsOpen(v=>!v)} className="relative rounded-lg p-2 transition-colors hover:bg-glass-bg" aria-label="اعلان‌ها" aria-expanded={isOpen}><span aria-hidden="true">🔔</span>{unreadCount>0&&<span className="absolute -right-1 -top-1 flex h-5 min-w-5 items-center justify-center rounded-full bg-red-500 px-1 text-[10px] text-white">{unreadCount}</span>}</button><AnimatePresence initial={false}>{isOpen&&<motion.div initial={shouldReduceMotion?false:{opacity:0,y:-8,scale:.98}} animate={shouldReduceMotion?{}:{opacity:1,y:0,scale:1}} exit={shouldReduceMotion?{}:{opacity:0,y:-8,scale:.98}} transition={{duration:shouldReduceMotion?0:.18}} className="absolute right-0 z-50 mt-2 max-h-96 w-[min(20rem,calc(100vw-2rem))] overflow-y-auto rounded-xl glass shadow-xl sm:left-0 sm:right-auto"><div className="p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">اعلان‌ها</h3>{unreadCount>0&&<button type="button" onClick={markAllAsRead} className="text-xs text-primary-600 transition-colors hover:text-primary-700">خواندن همه</button>}</div>{notifications.length===0?<p className="py-8 text-center text-sm text-text-secondary">اعلانی وجود ندارد</p>:<div className="space-y-2">{notifications.map(n=><button type="button" key={n.id} onClick={()=>markAsRead(n.id)} className={`w-full rounded-lg p-3 text-right transition-colors hover:bg-glass-bg ${n.read?'opacity-70':'bg-primary-500/5'}`}><p className="text-sm">{n.title||n.message}</p>{n.title&&n.message&&<p className="mt-1 text-xs text-text-secondary">{n.message}</p>}<span className="text-xs text-text-secondary">{n.createdAt?new Date(n.createdAt).toLocaleDateString('fa-IR'):''}</span></button>)}</div>}</div></motion.div>}</AnimatePresence></div>
}
