const express = require('express')
const cors = require('cors')
const crypto = require('crypto')
const { Pool } = require('pg')

const app = express()
const PORT = Number(process.env.PORT || 3000)
const PREFIX = String(process.env.API_PREFIX || '/loloh').replace(/\/$/, '') || '/loloh'
const DATABASE_URL = String(process.env.DATABASE_URL || '').trim()
const AUTH_SECRET = String(process.env.AUTH_SECRET || '').trim()
const ADMIN_USERNAME = String(process.env.ADMIN_USERNAME || 'hirad990').trim().toLowerCase()
const ADMIN_PASSWORD = String(process.env.ADMIN_PASSWORD || '')

if (!DATABASE_URL) console.warn('DATABASE_URL is not configured.')
if (!AUTH_SECRET) console.warn('AUTH_SECRET is not configured.')
if (!ADMIN_PASSWORD) console.warn('ADMIN_PASSWORD is not configured. Admin login will be disabled.')

const pool = new Pool({ connectionString: DATABASE_URL || undefined, ssl: String(process.env.PGSSL).toLowerCase() === 'true' ? { rejectUnauthorized: false } : false, max: Number(process.env.PG_POOL_MAX || 10), idleTimeoutMillis: 30000, connectionTimeoutMillis: 10000 })
const allowedOrigins = ['https://binercraft.ir', 'https://www.binercraft.ir', 'http://localhost:5173', 'http://127.0.0.1:5173', ...(process.env.FRONTEND_URL || '').split(',').map(v => v.trim()).filter(Boolean)]
app.use(cors({ origin(origin, cb) { if (!origin || allowedOrigins.includes(origin) || /^https?:\/\/localhost(?::\d+)?$/.test(origin) || /^https?:\/\/127\.0\.0\.1(?::\d+)?$/.test(origin)) return cb(null, true); cb(new Error('CORS origin is not allowed')) }, credentials: true }))
app.use(express.json({ limit: '2mb' }))

// cPanel/Passenger may pass the mount prefix into req.url. Normalize both forms.
app.use((req, _res, next) => {
  if (req.url === PREFIX) req.url = '/'
  else if (req.url.startsWith(`${PREFIX}/`)) req.url = req.url.slice(PREFIX.length)
  next()
})

const q = (text, params = []) => pool.query(text, params)
const id = () => crypto.randomUUID()
const hashPassword = password => { const salt = crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}` }
const verifyPassword = (password, stored) => { if (!stored || !stored.includes(':')) return false; const [salt, hash] = stored.split(':'); try { return crypto.timingSafeEqual(Buffer.from(hash, 'hex'), crypto.scryptSync(password, salt, 64)) } catch { return false } }
const safeUser = row => { if (!row) return null; const { password_hash, ...user } = row; return user }
const signToken = payload => { const h = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url'); const b = Buffer.from(JSON.stringify(payload)).toString('base64url'); const s = crypto.createHmac('sha256', AUTH_SECRET).update(`${h}.${b}`).digest('base64url'); return `${h}.${b}.${s}` }
const verifyToken = token => { if (!token || !AUTH_SECRET) return null; const p = token.split('.'); if (p.length !== 3) return null; const expected = crypto.createHmac('sha256', AUTH_SECRET).update(`${p[0]}.${p[1]}`).digest('base64url'); if (p[2].length !== expected.length || !crypto.timingSafeEqual(Buffer.from(p[2]), Buffer.from(expected))) return null; try { const payload = JSON.parse(Buffer.from(p[1], 'base64url').toString()); return payload.exp > Math.floor(Date.now() / 1000) ? payload : null } catch { return null } }
const auth = (req, res, next) => { const raw = String(req.headers.authorization || ''); const user = verifyToken(raw.startsWith('Bearer ') ? raw.slice(7) : ''); if (!user) return res.status(401).json({ error: 'Authentication required' }); req.auth = user; next() }
const admin = (req, res, next) => auth(req, res, () => req.auth.role === 'admin' ? next() : res.status(403).json({ error: 'Admin access required' }))
const asyncRoute = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next)

async function initDatabase() {
  if (!DATABASE_URL) throw new Error('DATABASE_URL is required')
  await q(`CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, username varchar(32) UNIQUE NOT NULL, email varchar(320) UNIQUE, display_name varchar(80), role varchar(20) NOT NULL DEFAULT 'user', wallet bigint NOT NULL DEFAULT 0, avatar text DEFAULT '', password_hash text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE TABLE IF NOT EXISTS products (id uuid PRIMARY KEY, name varchar(180) NOT NULL, category varchar(80) DEFAULT '', price bigint NOT NULL DEFAULT 0, description text DEFAULT '', image text DEFAULT '', active boolean NOT NULL DEFAULT true, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE TABLE IF NOT EXISTS blog_posts (id uuid PRIMARY KEY, title varchar(180) NOT NULL, summary varchar(500) DEFAULT '', content text NOT NULL, author varchar(120) DEFAULT '', author_id uuid, date date NOT NULL DEFAULT current_date, likes integer NOT NULL DEFAULT 0, comments jsonb NOT NULL DEFAULT '[]'::jsonb, category varchar(80) DEFAULT '', image text DEFAULT '', published boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE TABLE IF NOT EXISTS cart_items (id uuid PRIMARY KEY, user_id varchar(128) NOT NULL DEFAULT 'guest', product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE, quantity integer NOT NULL DEFAULT 1, UNIQUE(user_id, product_id))`)
  await q(`CREATE TABLE IF NOT EXISTS discounts (id uuid PRIMARY KEY, code varchar(64) UNIQUE NOT NULL, description varchar(500) DEFAULT '', discount numeric NOT NULL DEFAULT 0, type varchar(20) NOT NULL DEFAULT 'percent', max_uses integer NOT NULL DEFAULT 0, used_count integer NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, expiry_date date, created_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE TABLE IF NOT EXISTS orders (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE SET NULL, username varchar(64) DEFAULT '', total bigint NOT NULL DEFAULT 0, status varchar(32) NOT NULL DEFAULT 'pending', payment_method varchar(32) DEFAULT '', payment_ref varchar(255) DEFAULT '', customer_data jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE TABLE IF NOT EXISTS order_items (id uuid PRIMARY KEY, order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id uuid REFERENCES products(id) ON DELETE SET NULL, name varchar(180) NOT NULL, price bigint NOT NULL, quantity integer NOT NULL DEFAULT 1)`)
  await q(`CREATE TABLE IF NOT EXISTS tickets (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE SET NULL, subject varchar(180) NOT NULL, message text NOT NULL, status varchar(32) NOT NULL DEFAULT 'open', priority varchar(20) NOT NULL DEFAULT 'normal', replies jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY, message text NOT NULL, type varchar(32) DEFAULT 'default', target_user_id uuid REFERENCES users(id) ON DELETE CASCADE, read boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE TABLE IF NOT EXISTS transactions (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id) ON DELETE SET NULL, order_id uuid REFERENCES orders(id) ON DELETE SET NULL, amount bigint NOT NULL, type varchar(32) NOT NULL, status varchar(32) NOT NULL DEFAULT 'completed', reference varchar(255) DEFAULT '', created_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE TABLE IF NOT EXISTS site_settings (id integer PRIMARY KEY DEFAULT 1, data jsonb NOT NULL DEFAULT '{}'::jsonb, updated_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE TABLE IF NOT EXISTS server_stats (id integer PRIMARY KEY DEFAULT 1, players integer NOT NULL DEFAULT 0, stability numeric NOT NULL DEFAULT 99.9, sales bigint NOT NULL DEFAULT 0, support integer NOT NULL DEFAULT 0, status varchar(32) NOT NULL DEFAULT 'online', updated_at timestamptz NOT NULL DEFAULT now())`)
  await q(`CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC); CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id); CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status); CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions(created_at DESC); CREATE INDEX IF NOT EXISTS idx_notifications_target ON notifications(target_user_id, read)`)
  await q(`INSERT INTO site_settings(id, data) VALUES(1, $1) ON CONFLICT(id) DO NOTHING`, [{ siteName:'BinerCraft', supportEmail:'support@binercraft.ir', supportHours:'هر روز، ۹ تا ۲۳', contactText:'تیم BinerCraft آماده پاسخ‌گویی به شماست.', serverAddress:'play.binercraft.ir', announcement:'' }])
  await q(`INSERT INTO server_stats(id) VALUES(1) ON CONFLICT(id) DO NOTHING`)
  if (ADMIN_PASSWORD) {
    const passwordHash = hashPassword(ADMIN_PASSWORD)
    await q(`INSERT INTO users(id, username, email, display_name, role, password_hash) VALUES($1,$2,$3,$4,'admin',$5) ON CONFLICT(username) DO UPDATE SET role='admin', password_hash=EXCLUDED.password_hash, updated_at=now()`, [id(), ADMIN_USERNAME, `${ADMIN_USERNAME}@binercraft.ir`, 'مدیر BinerCraft', passwordHash])
  }
}

const health = asyncRoute(async (_req, res) => { const result = await q('SELECT 1 AS ok'); res.json({ status:'ok', service:'BinerCraft Backend', database: result.rows[0].ok === 1 ? 'postgresql' : 'unknown', apiPrefix: PREFIX, timestamp:new Date().toISOString() }) })
app.get('/', health); app.get('/health', health); app.get('/api/health', health)

app.post('/api/auth/admin/login', asyncRoute(async (req,res) => { if (!ADMIN_PASSWORD || !AUTH_SECRET) return res.status(503).json({ error:'Admin authentication is not configured' }); const username=String(req.body.username||req.body.identifier||'').trim().toLowerCase(); if(username!==ADMIN_USERNAME || String(req.body.password||'')!==ADMIN_PASSWORD) return res.status(401).json({error:'Invalid admin credentials'}); const {rows}=await q('SELECT * FROM users WHERE username=$1 LIMIT 1',[ADMIN_USERNAME]); const user=rows[0]; const token=signToken({sub:user.id,username:user.username,role:'admin',exp:Math.floor(Date.now()/1000)+43200}); res.json({token,user:safeUser(user)}) }))
app.post('/api/users/register', asyncRoute(async(req,res)=>{const username=String(req.body.username||'').trim();const email=String(req.body.email||'').trim().toLowerCase();const password=String(req.body.password||'');if(!/^[-_a-zA-Z0-9]{3,32}$/.test(username)||password.length<8||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:'Invalid registration data'});const {rows}=await q('INSERT INTO users(id,username,email,display_name,password_hash) VALUES($1,$2,$3,$4,$5) RETURNING *',[id(),username,email,String(req.body.displayName||username).trim(),hashPassword(password)]);res.status(201).json({user:safeUser(rows[0])})}))
app.post('/api/users/login', asyncRoute(async(req,res)=>{const identifier=String(req.body.identifier||req.body.username||req.body.email||'').trim().toLowerCase();const {rows}=await q('SELECT * FROM users WHERE lower(username)=lower($1) OR lower(email)=lower($1) LIMIT 1',[identifier]);const user=rows[0];if(!user||!verifyPassword(String(req.body.password||''),user.password_hash))return res.status(401).json({error:'Invalid username/email or password'});const token=AUTH_SECRET?signToken({sub:user.id,username:user.username,role:user.role,exp:Math.floor(Date.now()/1000)+43200}):null;res.json({user:safeUser(user),...(token?{token}:{})})}))
app.get('/api/auth/me',auth,asyncRoute(async(req,res)=>{const {rows}=await q('SELECT * FROM users WHERE id=$1',[req.auth.sub]);if(!rows[0])return res.status(401).json({error:'User not found'});res.json({user:safeUser(rows[0])})}))

app.get('/api/users',admin,asyncRoute(async(_req,res)=>res.json((await q('SELECT * FROM users ORDER BY created_at DESC')).rows.map(safeUser))))
app.post('/api/users',admin,asyncRoute(async(req,res)=>{const body=req.body||{};const {rows}=await q('INSERT INTO users(id,username,email,display_name,role,wallet,avatar,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[id(),String(body.username||'').trim(),String(body.email||'').trim().toLowerCase()||null,String(body.displayName||body.username||'').trim(),body.role==='admin'?'admin':'user',Number(body.wallet||0),String(body.avatar||''),body.password?hashPassword(String(body.password)):null]);res.status(201).json(safeUser(rows[0]))}))
app.patch('/api/users/:id',admin,asyncRoute(async(req,res)=>{const b=req.body||{};const fields=[];const vals=[];const set=(k,v)=>{fields.push(`${k}=$${vals.length+1}`);vals.push(v)};if(b.email!==undefined)set('email',String(b.email).trim().toLowerCase()||null);if(b.displayName!==undefined)set('display_name',String(b.displayName).trim());if(b.role!==undefined)set('role',b.role==='admin'?'admin':'user');if(b.wallet!==undefined)set('wallet',Number(b.wallet));if(b.avatar!==undefined)set('avatar',String(b.avatar||''));if(b.password)set('password_hash',hashPassword(String(b.password)));if(!fields.length)return res.status(400).json({error:'No changes supplied'});set('updated_at',new Date());vals.push(req.params.id);const {rows}=await q(`UPDATE users SET ${fields.join(',')} WHERE id=$${vals.length} RETURNING *`,vals);if(!rows[0])return res.status(404).json({error:'User not found'});res.json(safeUser(rows[0]))}))
app.delete('/api/users/:id',admin,asyncRoute(async(req,res)=>{if(String(req.params.id)===String(req.auth.sub))return res.status(400).json({error:'You cannot delete your own account'});await q('DELETE FROM users WHERE id=$1',[req.params.id]);res.status(204).send()}))
app.patch('/api/account',auth,asyncRoute(async(req,res)=>{const b=req.body||{};const {rows}=await q('UPDATE users SET display_name=COALESCE($1,display_name),email=COALESCE($2,email),username=COALESCE($3,username),avatar=COALESCE($4,avatar),password_hash=CASE WHEN $5 IS NULL THEN password_hash ELSE $5 END,updated_at=now() WHERE id=$6 RETURNING *',[b.displayName===undefined?null:String(b.displayName).trim(),b.email===undefined?null:String(b.email).trim().toLowerCase(),b.username===undefined?null:String(b.username).trim(),b.avatar===undefined?null:String(b.avatar||''),b.password?hashPassword(String(b.password)):null,req.auth.sub]);res.json(safeUser(rows[0]))}))

app.get('/api/products',asyncRoute(async(_req,res)=>res.json((await q('SELECT id,name,category,price,description,image,active,metadata,created_at AS "createdAt" FROM products WHERE active=true ORDER BY created_at DESC')).rows)))
app.get('/api/products/all',admin,asyncRoute(async(_req,res)=>res.json((await q('SELECT * FROM products ORDER BY created_at DESC')).rows)))
app.post('/api/products',admin,asyncRoute(async(req,res)=>{const b=req.body||{};const {rows}=await q('INSERT INTO products(id,name,category,price,description,image,metadata) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[id(),String(b.name||''),String(b.category||''),Number(b.price||0),String(b.description||''),String(b.image||''),b.metadata||{}]);res.status(201).json(rows[0])}))
app.patch('/api/products/:id',admin,asyncRoute(async(req,res)=>{const b=req.body||{};const {rows}=await q('UPDATE products SET name=COALESCE($1,name),category=COALESCE($2,category),price=COALESCE($3,price),description=COALESCE($4,description),image=COALESCE($5,image),active=COALESCE($6,active),metadata=COALESCE($7,metadata),updated_at=now() WHERE id=$8 RETURNING *',[b.name??null,b.category??null,b.price===undefined?null:Number(b.price),b.description??null,b.image??null,b.active===undefined?null:Boolean(b.active),b.metadata??null,req.params.id]);if(!rows[0])return res.status(404).json({error:'Product not found'});res.json(rows[0])}))
app.delete('/api/products/:id',admin,asyncRoute(async(req,res)=>{await q('DELETE FROM products WHERE id=$1',[req.params.id]);res.status(204).send()}))

app.get('/api/blog',asyncRoute(async(_req,res)=>res.json((await q('SELECT id,title,summary,content,author,author_id AS "authorId",date,likes,comments,category,image,published FROM blog_posts WHERE published=true ORDER BY date DESC,created_at DESC')).rows)))
app.post('/api/blog',auth,asyncRoute(async(req,res)=>{const b=req.body||{};const {rows}=await q('INSERT INTO blog_posts(id,title,summary,content,author,author_id,category,image,published) VALUES($1,$2,$3,$4,(SELECT display_name FROM users WHERE id=$5),$5,$6,$7,$8) RETURNING *',[id(),String(b.title||''),String(b.summary||'').slice(0,500),String(b.content||''),req.auth.sub,String(b.category||'مطالب کاربران'),String(b.image||''),b.published!==false]);res.status(201).json(rows[0])}))
app.patch('/api/blog/:id',admin,asyncRoute(async(req,res)=>{const b=req.body||{};const {rows}=await q('UPDATE blog_posts SET title=COALESCE($1,title),summary=COALESCE($2,summary),content=COALESCE($3,content),category=COALESCE($4,category),image=COALESCE($5,image),published=COALESCE($6,published),updated_at=now() WHERE id=$7 RETURNING *',[b.title??null,b.summary??null,b.content??null,b.category??null,b.image??null,b.published===undefined?null:Boolean(b.published),req.params.id]);if(!rows[0])return res.status(404).json({error:'Post not found'});res.json(rows[0])}))
app.delete('/api/blog/:id',admin,asyncRoute(async(req,res)=>{await q('DELETE FROM blog_posts WHERE id=$1',[req.params.id]);res.status(204).send()}))

app.get('/api/site-settings',asyncRoute(async(_req,res)=>res.json((await q('SELECT data FROM site_settings WHERE id=1')).rows[0]?.data||{})))
app.patch('/api/site-settings',admin,asyncRoute(async(req,res)=>{const {rows}=await q('UPDATE site_settings SET data=$1,updated_at=now() WHERE id=1 RETURNING data',[req.body||{}]);res.json(rows[0].data)}))
app.get('/api/server-stats',asyncRoute(async(_req,res)=>{const {rows}=await q('SELECT players,stability,sales,support,status FROM server_stats WHERE id=1');res.json(rows[0]||{})}))
app.patch('/api/server-stats',admin,asyncRoute(async(req,res)=>{const b=req.body||{};const {rows}=await q('UPDATE server_stats SET players=COALESCE($1,players),stability=COALESCE($2,stability),sales=COALESCE($3,sales),support=COALESCE($4,support),status=COALESCE($5,status),updated_at=now() WHERE id=1 RETURNING players,stability,sales,support,status',[b.players===undefined?null:Number(b.players),b.stability===undefined?null:Number(b.stability),b.sales===undefined?null:Number(b.sales),b.support===undefined?null:Number(b.support),b.status??null]);res.json(rows[0])}))

app.get('/api/cart',asyncRoute(async(req,res)=>{const uid=String(req.query.userId||'guest');res.json((await q('SELECT c.id,c.user_id AS "userId",c.product_id AS "productId",c.quantity,p.name,p.price,p.image FROM cart_items c JOIN products p ON p.id=c.product_id WHERE c.user_id=$1 ORDER BY p.name',[uid])).rows)}))
app.post('/api/cart',asyncRoute(async(req,res)=>{const uid=String(req.body.userId||'guest');const pid=String(req.body.productId||'');const qty=Math.max(1,Number(req.body.quantity||1));const {rows}=await q('INSERT INTO cart_items(id,user_id,product_id,quantity) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,product_id) DO UPDATE SET quantity=cart_items.quantity+EXCLUDED.quantity RETURNING *',[id(),uid,pid,qty]);res.status(201).json(rows[0])}))
app.patch('/api/cart/:id',asyncRoute(async(req,res)=>{const {rows}=await q('UPDATE cart_items SET quantity=$1 WHERE id=$2 RETURNING *',[Math.max(1,Number(req.body.quantity||1)),req.params.id]);if(!rows[0])return res.status(404).json({error:'Cart item not found'});res.json(rows[0])}))
app.delete('/api/cart/:id',asyncRoute(async(req,res)=>{await q('DELETE FROM cart_items WHERE id=$1',[req.params.id]);res.status(204).send()}))

app.get('/api/discounts',admin,asyncRoute(async(_req,res)=>res.json((await q('SELECT * FROM discounts ORDER BY created_at DESC')).rows)))
app.post('/api/discounts',admin,asyncRoute(async(req,res)=>{const b=req.body||{};const {rows}=await q('INSERT INTO discounts(id,code,description,discount,type,max_uses,active,expiry_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[id(),String(b.code||'').trim().toUpperCase(),String(b.description||''),Number(b.discount||0),b.type==='fixed'?'fixed':'percent',Number(b.maxUses||0),b.active!==false,b.expiryDate||null]);res.status(201).json(rows[0])}))
app.patch('/api/discounts/:id',admin,asyncRoute(async(req,res)=>{const b=req.body||{};const {rows}=await q('UPDATE discounts SET description=COALESCE($1,description),discount=COALESCE($2,discount),type=COALESCE($3,type),max_uses=COALESCE($4,max_uses),active=COALESCE($5,active),expiry_date=COALESCE($6,expiry_date) WHERE id=$7 RETURNING *',[b.description??null,b.discount===undefined?null:Number(b.discount),b.type??null,b.maxUses===undefined?null:Number(b.maxUses),b.active===undefined?null:Boolean(b.active),b.expiryDate??null,req.params.id]);if(!rows[0])return res.status(404).json({error:'Discount not found'});res.json(rows[0])}))
app.delete('/api/discounts/:id',admin,asyncRoute(async(req,res)=>{await q('DELETE FROM discounts WHERE id=$1',[req.params.id]);res.status(204).send()}))
app.post('/api/discounts/apply',asyncRoute(async(req,res)=>{const code=String(req.body.code||'').trim().toUpperCase();const {rows}=await q('SELECT * FROM discounts WHERE code=$1 AND active=true AND (expiry_date IS NULL OR expiry_date>=CURRENT_DATE) AND (max_uses=0 OR used_count<max_uses)',[code]);if(!rows[0])return res.status(404).json({error:'Invalid or expired discount'});res.json(rows[0])}))

app.get('/api/orders',admin,asyncRoute(async(_req,res)=>res.json((await q('SELECT id,user_id AS "userId",username,total,status,payment_method AS "paymentMethod",payment_ref AS "paymentRef",customer_data AS "customerData",created_at AS "createdAt" FROM orders ORDER BY created_at DESC')).rows)))
app.post('/api/orders',auth,asyncRoute(async(req,res)=>{const b=req.body||{};const items=Array.isArray(b.items)?b.items:[];if(!items.length)return res.status(400).json({error:'Order is empty'});const client=await pool.connect();try{await client.query('BEGIN');let total=0;for(const item of items)total+=Number(item.price||0)*Math.max(1,Number(item.quantity||1));const oid=id();await client.query('INSERT INTO orders(id,user_id,username,total,status,payment_method,customer_data) VALUES($1,$2,$3,$4,$5,$6,$7)',[oid,req.auth.sub,req.auth.username,total,String(b.status||'pending'),String(b.paymentMethod||''),b.customerData||{}]);for(const item of items)await client.query('INSERT INTO order_items(id,order_id,product_id,name,price,quantity) VALUES($1,$2,$3,$4,$5,$6)',[id(),oid,item.productId||null,String(item.name||'محصول'),Number(item.price||0),Math.max(1,Number(item.quantity||1))]);await client.query('COMMIT');res.status(201).json({id:oid,total,status:'pending'})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}))
app.patch('/api/orders/:id',admin,asyncRoute(async(req,res)=>{const {rows}=await q('UPDATE orders SET status=COALESCE($1,status),payment_ref=COALESCE($2,payment_ref),updated_at=now() WHERE id=$3 RETURNING *',[req.body.status??null,req.body.paymentRef??null,req.params.id]);if(!rows[0])return res.status(404).json({error:'Order not found'});res.json(rows[0])}))
app.post('/api/pay-with-wallet',auth,asyncRoute(async(req,res)=>{const amount=Number(req.body.amount||0);if(amount<=0)return res.status(400).json({error:'Invalid amount'});const client=await pool.connect();try{await client.query('BEGIN');const user=(await client.query('SELECT wallet FROM users WHERE id=$1 FOR UPDATE',[req.auth.sub])).rows[0];if(!user||Number(user.wallet)<amount){await client.query('ROLLBACK');return res.status(400).json({error:'Insufficient wallet balance'})}await client.query('UPDATE users SET wallet=wallet-$1,updated_at=now() WHERE id=$2',[amount,req.auth.sub]);const tx=id();await client.query('INSERT INTO transactions(id,user_id,amount,type,status,reference) VALUES($1,$2,$3,$4,$5,$6)',[tx,req.auth.sub,amount,'wallet_payment','completed',String(req.body.orderId||'')]);await client.query('COMMIT');res.json({success:true,transactionId:tx})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}))
app.post('/api/create-bale-invoice',auth,asyncRoute(async(req,res)=>{const amount=Number(req.body.amount||0);if(!amount)return res.status(400).json({error:'Invalid amount'});if(!process.env.BALE_PAYMENT_URL)return res.status(503).json({error:'Bale payment is not configured'});res.json({success:true,paymentUrl:process.env.BALE_PAYMENT_URL,amount})}))

app.get('/api/tickets',admin,asyncRoute(async(_req,res)=>res.json((await q('SELECT * FROM tickets ORDER BY created_at DESC')).rows)))
app.post('/api/tickets',auth,asyncRoute(async(req,res)=>{const {rows}=await q('INSERT INTO tickets(id,user_id,subject,message,priority) VALUES($1,$2,$3,$4,$5) RETURNING *',[id(),req.auth.sub,String(req.body.subject||''),String(req.body.message||''),String(req.body.priority||'normal')]);res.status(201).json(rows[0])}))
app.patch('/api/tickets/:id',admin,asyncRoute(async(req,res)=>{const {rows}=await q('UPDATE tickets SET status=COALESCE($1,status),priority=COALESCE($2,priority),replies=COALESCE($3,replies),updated_at=now() WHERE id=$4 RETURNING *',[req.body.status??null,req.body.priority??null,req.body.replies??null,req.params.id]);if(!rows[0])return res.status(404).json({error:'Ticket not found'});res.json(rows[0])}))

app.get('/api/admin/overview',admin,asyncRoute(async(_req,res)=>{const [users,products,posts,orders,tickets,revenue,stats]=await Promise.all([q('SELECT count(*)::int n FROM users'),q('SELECT count(*)::int n FROM products WHERE active=true'),q('SELECT count(*)::int n FROM blog_posts'),q('SELECT count(*)::int n FROM orders'),q("SELECT count(*)::int n FROM tickets WHERE status NOT IN ('closed','resolved')"),q("SELECT COALESCE(sum(total),0)::bigint n FROM orders WHERE status IN ('paid','completed')"),q('SELECT players,stability,sales,support,status FROM server_stats WHERE id=1')]);res.json({users:users.rows[0].n,products:products.rows[0].n,posts:posts.rows[0].n,orders:orders.rows[0].n,openTickets:tickets.rows[0].n,revenue:revenue.rows[0].n,serverStats:stats.rows[0]})}))

// Admin-only database inspection/control for supported application tables.
const adminTables={users:'users',products:'products',blog:'blog_posts',orders:'orders',tickets:'tickets',discounts:'discounts',transactions:'transactions',notifications:'notifications',cart:'cart_items'}
app.get('/api/admin/data/:table',admin,asyncRoute(async(req,res)=>{const table=adminTables[req.params.table];if(!table)return res.status(404).json({error:'Unsupported table'});const {rows}=await q(`SELECT * FROM ${table} ORDER BY 1 DESC LIMIT 1000`);res.json(rows)}))

app.use((req,res)=>res.status(404).json({error:'Route not found',path:req.path,prefix:PREFIX}))
app.use((err,_req,res,_next)=>{console.error(err);res.status(err.code&&Number(err.code)>=400?Number(err.code):500).json({error:process.env.NODE_ENV==='production'?'Internal server error':err.message})})

async function start(){await initDatabase();await q('SELECT 1');app.listen(PORT,()=>console.log(`BinerCraft backend listening on ${PORT} with PostgreSQL at ${PREFIX}`))}
start().catch(error=>{console.error('Backend startup failed:',error);process.exit(1)})
process.on('SIGTERM',async()=>{await pool.end();process.exit(0)})
process.on('SIGINT',async()=>{await pool.end();process.exit(0)})
