const express=require('express')
const cors=require('cors')
const crypto=require('crypto')
const mysql=require('mysql2/promise')
const app=express()
const PORT=Number(process.env.PORT||3000)
const PREFIX=(String(process.env.API_PREFIX||'/loloh').replace(/\/$/,'')||'/loloh')
const SECRET=String(process.env.AUTH_SECRET||'').trim()
const ADMIN=String(process.env.ADMIN_USERNAME||'hirad990').trim().toLowerCase()
const ADMIN_PASSWORD=String(process.env.ADMIN_PASSWORD||'')
const pool=mysql.createPool({host:process.env.DB_HOST||'localhost',port:Number(process.env.DB_PORT||3306),database:process.env.DB_NAME||'',user:process.env.DB_USER||'',password:process.env.DB_PASSWORD||'',waitForConnections:true,connectionLimit:Number(process.env.DB_CONNECTION_LIMIT||10),charset:'utf8mb4'})
const origins=['https://binercraft.ir','https://www.binercraft.ir','http://localhost:5173','http://127.0.0.1:5173',...(process.env.FRONTEND_URL||'').split(',').map(x=>x.trim()).filter(Boolean)]
app.use(cors({origin:(o,cb)=>!o||origins.includes(o)||/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(o)?cb(null,true):cb(new Error('CORS origin is not allowed')),credentials:true}))
app.use(express.json({limit:'2mb'}))
app.use((req,_res,next)=>{if(req.url===PREFIX)req.url='/';else if(req.url.startsWith(PREFIX+'/'))req.url=req.url.slice(PREFIX.length);next()})
const q=(s,p=[])=>pool.execute(s,p)
const uid=()=>crypto.randomUUID()
const j=v=>JSON.stringify(v??{})
const pj=v=>{if(v==null||v==='')return {};if(typeof v==='object')return v;try{return JSON.parse(v)}catch{return {}}}
const pa=v=>{const x=pj(v);return Array.isArray(x)?x:[]}
const hash=p=>{const s=crypto.randomBytes(16).toString('hex');return `${s}:${crypto.scryptSync(p,s,64).toString('hex')}`}
const verify=(p,h)=>{if(!h||!h.includes(':'))return false;const [s,x]=h.split(':');try{const a=crypto.scryptSync(p,s,64),b=Buffer.from(x,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}}
const safe=u=>{if(!u)return null;const {password_hash,...x}=u;return {...x,wallet:Number(x.wallet||0)}}
const token=p=>{const h=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),b=Buffer.from(JSON.stringify(p)).toString('base64url'),s=crypto.createHmac('sha256',SECRET).update(`${h}.${b}`).digest('base64url');return `${h}.${b}.${s}`}
const decode=t=>{if(!t||!SECRET)return null;const a=t.split('.');if(a.length!==3)return null;const b=Buffer.from(crypto.createHmac('sha256',SECRET).update(`${a[0]}.${a[1]}`).digest('base64url')),c=Buffer.from(a[2]);if(b.length!==c.length||!crypto.timingSafeEqual(b,c))return null;try{const p=JSON.parse(Buffer.from(a[1],'base64url'));return p.exp>Date.now()/1000?p:null}catch{return null}}
const auth=(req,res,next)=>{const h=String(req.headers.authorization||'');const u=decode(h.startsWith('Bearer ')?h.slice(7):'');if(!u)return res.status(401).json({error:'Authentication required'});req.auth=u;next()}
const admin=(req,res,next)=>auth(req,res,()=>req.auth.role==='admin'?next():res.status(403).json({error:'Admin access required'}))
const route=f=>(req,res,next)=>Promise.resolve(f(req,res,next)).catch(next)

async function schema(){
 if(!process.env.DB_NAME||!process.env.DB_USER)throw Error('DB_NAME and DB_USER are required')
 await q(`CREATE TABLE IF NOT EXISTS users(id varchar(64) PRIMARY KEY,username varchar(32) UNIQUE NOT NULL,email varchar(320) UNIQUE,display_name varchar(80),role varchar(20) NOT NULL DEFAULT 'user',wallet BIGINT NOT NULL DEFAULT 0,avatar text,password_hash text,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS products(id varchar(64) PRIMARY KEY,name varchar(180) NOT NULL,category varchar(80) DEFAULT '',price BIGINT NOT NULL DEFAULT 0,description text,image text,active TINYINT(1) NOT NULL DEFAULT 1,metadata JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(active),INDEX(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS blog_posts(id varchar(64) PRIMARY KEY,title varchar(180) NOT NULL,summary varchar(500),content LONGTEXT NOT NULL,author varchar(120),author_id varchar(64),date DATE NOT NULL,likes INT NOT NULL DEFAULT 0,comments JSON NULL,category varchar(80),image text,published TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(published),INDEX(date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS cart_items(id varchar(64) PRIMARY KEY,user_id varchar(128) NOT NULL DEFAULT 'guest',product_id varchar(64) NOT NULL,quantity INT NOT NULL DEFAULT 1,UNIQUE KEY cart_user_product(user_id,product_id),CONSTRAINT cart_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS discounts(id varchar(64) PRIMARY KEY,code varchar(64) UNIQUE NOT NULL,description varchar(500),discount DECIMAL(12,2) NOT NULL DEFAULT 0,type varchar(20) NOT NULL DEFAULT 'percent',max_uses INT NOT NULL DEFAULT 0,used_count INT NOT NULL DEFAULT 0,active TINYINT(1) NOT NULL DEFAULT 1,expiry_date DATE NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS orders(id varchar(64) PRIMARY KEY,user_id varchar(64),username varchar(64) DEFAULT '',total BIGINT NOT NULL DEFAULT 0,status varchar(32) NOT NULL DEFAULT 'pending',payment_method varchar(32) DEFAULT '',payment_ref varchar(255) DEFAULT '',customer_data JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(created_at),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS order_items(id varchar(64) PRIMARY KEY,order_id varchar(64) NOT NULL,product_id varchar(64),name varchar(180) NOT NULL,price BIGINT NOT NULL DEFAULT 0,quantity INT NOT NULL DEFAULT 1,INDEX(order_id),CONSTRAINT order_items_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS tickets(id varchar(64) PRIMARY KEY,user_id varchar(64),subject varchar(180) NOT NULL,message LONGTEXT NOT NULL,status varchar(32) NOT NULL DEFAULT 'open',priority varchar(20) NOT NULL DEFAULT 'normal',replies JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(status),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS notifications(id varchar(64) PRIMARY KEY,message text NOT NULL,type varchar(32) DEFAULT 'default',target_user_id varchar(64),is_read TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(target_user_id,is_read)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS transactions(id varchar(64) PRIMARY KEY,user_id varchar(64),order_id varchar(64),amount BIGINT NOT NULL,type varchar(32) NOT NULL,status varchar(32) NOT NULL DEFAULT 'completed',reference_code varchar(255) DEFAULT '',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(created_at),INDEX(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS site_settings(id TINYINT PRIMARY KEY,data JSON NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q(`CREATE TABLE IF NOT EXISTS server_stats(id TINYINT PRIMARY KEY,players INT NOT NULL DEFAULT 0,stability DECIMAL(5,2) NOT NULL DEFAULT 99.90,sales BIGINT NOT NULL DEFAULT 0,support INT NOT NULL DEFAULT 0,status varchar(32) NOT NULL DEFAULT 'online',updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`)
 await q('INSERT IGNORE INTO site_settings(id,data) VALUES(1,?)',[j({siteName:'BinerCraft',supportEmail:'support@binercraft.ir',supportHours:'هر روز، ۹ تا ۲۳',contactText:'تیم BinerCraft آماده پاسخ‌گویی به شماست.',serverAddress:'play.binercraft.ir',announcement:''})])
 await q('INSERT IGNORE INTO server_stats(id) VALUES(1)')
 if(ADMIN_PASSWORD&&SECRET){const [r]=await q('SELECT id FROM users WHERE username=?',[ADMIN]);const aid=r[0]?.id||uid();await q(`INSERT INTO users(id,username,email,display_name,role,password_hash) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE role='admin',password_hash=VALUES(password_hash),updated_at=CURRENT_TIMESTAMP`,[aid,ADMIN,`${ADMIN}@binercraft.ir`,'مدیر BinerCraft','admin',hash(ADMIN_PASSWORD)])}
}

const health=route(async(_req,res)=>{await q('SELECT 1');res.json({status:'ok',service:'BinerCraft Backend',database:'mysql',apiPrefix:PREFIX,timestamp:new Date().toISOString()})})
app.get('/',health);app.get('/health',health);app.get('/api/health',health)

app.post('/api/auth/admin/login',route(async(req,res)=>{const [r]=await q("SELECT * FROM users WHERE LOWER(username)=? AND role='admin' LIMIT 1",[String(req.body.username||req.body.identifier||'').trim().toLowerCase()]);const u=r[0];if(!u||!verify(String(req.body.password||''),u.password_hash))return res.status(401).json({error:'Invalid admin credentials'});if(!SECRET)return res.status(503).json({error:'AUTH_SECRET is not configured'});res.json({token:token({sub:u.id,username:u.username,role:'admin',exp:Math.floor(Date.now()/1000)+43200}),user:safe(u)})}))
app.post('/api/users/register',route(async(req,res)=>{const username=String(req.body.username||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!/^[-_a-zA-Z0-9]{3,32}$/.test(username)||password.length<8||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:'Invalid registration data'});const id=newId(),displayName=String(req.body.displayName||username).trim();await q('INSERT INTO users(id,username,email,display_name,password_hash) VALUES(?,?,?,?,?)',[id,username,email,displayName,hash(password)]);const [r]=await q('SELECT * FROM users WHERE id=?',[id]);res.status(201).json({user:safe(r[0])})}))
app.post('/api/users/login',route(async(req,res)=>{const x=String(req.body.identifier||req.body.username||req.body.email||'').trim().toLowerCase();const [r]=await q('SELECT * FROM users WHERE LOWER(username)=? OR LOWER(email)=? LIMIT 1',[x,x]);const u=r[0];if(!u||!verify(String(req.body.password||''),u.password_hash))return res.status(401).json({error:'Invalid username/email or password'});const t=SECRET?token({sub:u.id,username:u.username,role:u.role,exp:Math.floor(Date.now()/1000)+43200}):null;res.json({user:safe(u),...(t?{token:t}:{})})}))
app.get('/api/auth/me',auth,route(async(req,res)=>{const [r]=await q('SELECT * FROM users WHERE id=?',[req.auth.sub]);if(!r[0])return res.status(401).json({error:'User not found'});res.json({user:safe(r[0])})}))

app.get('/api/users',admin,route(async(_req,res)=>{const [r]=await q('SELECT * FROM users ORDER BY created_at DESC');res.json(r.map(safe))}))
app.post('/api/users',admin,route(async(req,res)=>{const b=req.body||{},id=newId();await q('INSERT INTO users(id,username,email,display_name,role,wallet,avatar,password_hash) VALUES(?,?,?,?,?,?,?,?)',[id,String(b.username||'').trim(),String(b.email||'').trim().toLowerCase()||null,String(b.displayName||b.username||'').trim(),b.role==='admin'?'admin':'user',Number(b.wallet||0),String(b.avatar||''),b.password?hash(String(b.password)):null]);const [r]=await q('SELECT * FROM users WHERE id=?',[id]);res.status(201).json(safe(r[0]))}))
app.patch('/api/users/:id',admin,route(async(req,res)=>{const b=req.body||{},sets=[],vals=[];const put=(k,v)=>{sets.push(`${k}=?`);vals.push(v)};if(b.email!==undefined)put('email',String(b.email).trim().toLowerCase()||null);if(b.displayName!==undefined)put('display_name',String(b.displayName).trim());if(b.role!==undefined)put('role',b.role==='admin'?'admin':'user');if(b.wallet!==undefined)put('wallet',Number(b.wallet));if(b.avatar!==undefined)put('avatar',String(b.avatar||''));if(b.password)put('password_hash',hash(String(b.password)));if(!sets.length)return res.status(400).json({error:'No changes supplied'});vals.push(req.params.id);await q(`UPDATE users SET ${sets.join(',')} WHERE id=?`,vals);const [r]=await q('SELECT * FROM users WHERE id=?',[req.params.id]);if(!r[0])return res.status(404).json({error:'User not found'});res.json(safe(r[0]))}))
app.delete('/api/users/:id',admin,route(async(req,res)=>{if(String(req.params.id)===String(req.auth.sub))return res.status(400).json({error:'You cannot delete your own account'});await q('DELETE FROM users WHERE id=?',[req.params.id]);res.status(204).send()}))
app.patch('/api/account',auth,route(async(req,res)=>{const b=req.body||{},sets=[],vals=[];const put=(k,v)=>{sets.push(`${k}=?`);vals.push(v)};if(b.displayName!==undefined)put('display_name',String(b.displayName).trim());if(b.email!==undefined)put('email',String(b.email).trim().toLowerCase());if(b.username!==undefined)put('username',String(b.username).trim());if(b.avatar!==undefined)put('avatar',String(b.avatar||''));if(b.password)put('password_hash',hash(String(b.password)));if(!sets.length)return res.status(400).json({error:'No changes supplied'});vals.push(req.auth.sub);await q(`UPDATE users SET ${sets.join(',')} WHERE id=?`,vals);const [r]=await q('SELECT * FROM users WHERE id=?',[req.auth.sub]);res.json(safe(r[0]))}))

app.get('/api/products',route(async(_req,res)=>{const [r]=await q('SELECT * FROM products WHERE active=1 ORDER BY created_at DESC');res.json(r.map(x=>({...x,price:Number(x.price),metadata:pj(x.metadata)})))}))
app.get('/api/products/all',admin,route(async(_req,res)=>{const [r]=await q('SELECT * FROM products ORDER BY created_at DESC');res.json(r.map(x=>({...x,price:Number(x.price),metadata:pj(x.metadata)})))}))
app.post('/api/products',admin,route(async(req,res)=>{const b=req.body||{},id=newId();await q('INSERT INTO products(id,name,category,price,description,image,active,metadata) VALUES(?,?,?,?,?,?,?,?)',[id,String(b.name||''),String(b.category||''),Number(b.price||0),String(b.description||''),String(b.image||''),b.active===false?0:1,j(b.metadata)]);const [r]=await q('SELECT * FROM products WHERE id=?',[id]);res.status(201).json(r[0])}))
app.patch('/api/products/:id',admin,route(async(req,res)=>{const b=req.body||{},sets=[],vals=[];const put=(k,v)=>{sets.push(`${k}=?`);vals.push(v)};for(const [a,c] of [['name','name'],['category','category'],['description','description'],['image','image']])if(b[a]!==undefined)put(c,String(b[a]||''));if(b.price!==undefined)put('price',Number(b.price));if(b.active!==undefined)put('active',b.active?1:0);if(b.metadata!==undefined)put('metadata',j(b.metadata));if(!sets.length)return res.status(400).json({error:'No changes supplied'});vals.push(req.params.id);await q(`UPDATE products SET ${sets.join(',')} WHERE id=?`,vals);const [r]=await q('SELECT * FROM products WHERE id=?',[req.params.id]);if(!r[0])return res.status(404).json({error:'Product not found'});res.json(r[0])}))
app.delete('/api/products/:id',admin,route(async(req,res)=>{await q('DELETE FROM products WHERE id=?',[req.params.id]);res.status(204).send()}))

app.get('/api/blog',route(async(_req,res)=>{const [r]=await q('SELECT * FROM blog_posts WHERE published=1 ORDER BY date DESC,created_at DESC');res.json(r.map(x=>({...x,comments:pa(x.comments)})))}))
app.post('/api/blog',auth,route(async(req,res)=>{const b=req.body||{},id=newId();await q('INSERT INTO blog_posts(id,title,summary,content,author,author_id,date,comments,category,image,published) VALUES(?,?,?,?,?,?,COALESCE(?,CURDATE()),?,?,?,?)',[id,String(b.title||''),String(b.summary||''),String(b.content||''),String(b.author||req.auth.username),req.auth.sub,b.date||null,j(b.comments||[]),String(b.category||''),String(b.image||''),b.published===false?0:1]);const [r]=await q('SELECT * FROM blog_posts WHERE id=?',[id]);res.status(201).json(r[0])}))
app.patch('/api/blog/:id',admin,route(async(req,res)=>{const b=req.body||{},sets=[],vals=[];const map={title:'title',summary:'summary',content:'content',author:'author',authorId:'author_id',date:'date',category:'category',image:'image'};for(const k of Object.keys(map))if(b[k]!==undefined){sets.push(`${map[k]}=?`);vals.push(b[k])}if(b.published!==undefined){sets.push('published=?');vals.push(b.published?1:0)}if(b.comments!==undefined){sets.push('comments=?');vals.push(j(b.comments))}if(!sets.length)return res.status(400).json({error:'No changes supplied'});vals.push(req.params.id);await q(`UPDATE blog_posts SET ${sets.join(',')} WHERE id=?`,vals);const [r]=await q('SELECT * FROM blog_posts WHERE id=?',[req.params.id]);res.json(r[0])}))
app.delete('/api/blog/:id',admin,route(async(req,res)=>{await q('DELETE FROM blog_posts WHERE id=?',[req.params.id]);res.status(204).send()}))

app.get('/api/site-settings',route(async(_req,res)=>{const [r]=await q('SELECT data FROM site_settings WHERE id=1');res.json(pj(r[0]?.data))}))
app.patch('/api/site-settings',admin,route(async(req,res)=>{await q('UPDATE site_settings SET data=? WHERE id=1',[j(req.body||{})]);res.json(req.body||{})}))
app.get('/api/server-stats',route(async(_req,res)=>{const [r]=await q('SELECT * FROM server_stats WHERE id=1');const x=r[0]||{};res.json({...x,players:Number(x.players||0),stability:Number(x.stability||0),sales:Number(x.sales||0),support:Number(x.support||0)})}))
app.patch('/api/server-stats',admin,route(async(req,res)=>{const b=req.body||{};await q('UPDATE server_stats SET players=?,stability=?,sales=?,support=?,status=? WHERE id=1',[Number(b.players||0),Number(b.stability||0),Number(b.sales||0),Number(b.support||0),String(b.status||'online')]);const [r]=await q('SELECT * FROM server_stats WHERE id=1');res.json(r[0])}))

app.get('/api/cart',route(async(req,res)=>{const userId=req.auth?.sub||String(req.query.userId||'guest');const [r]=await q('SELECT c.id,c.user_id userId,c.product_id productId,c.quantity,p.name,p.category,p.price,p.image,p.description FROM cart_items c JOIN products p ON p.id=c.product_id WHERE c.user_id=?',[userId]);res.json(r.map(x=>({...x,price:Number(x.price)})))}))
app.post('/api/cart',route(async(req,res)=>{const userId=req.auth?.sub||String(req.body.userId||'guest'),productId=String(req.body.productId||req.body.id||''),quantity=Math.max(1,Number(req.body.quantity||1));if(!productId)return res.status(400).json({error:'productId is required'});await q('INSERT INTO cart_items(id,user_id,product_id,quantity) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE quantity=quantity+VALUES(quantity)',[uid(),userId,productId,quantity]);const [r]=await q('SELECT * FROM cart_items WHERE user_id=? AND product_id=?',[userId,productId]);res.json(r[0])}))
app.patch('/api/cart/:id',route(async(req,res)=>{await q('UPDATE cart_items SET quantity=? WHERE id=?',[Math.max(1,Number(req.body.quantity||1)),req.params.id]);const [r]=await q('SELECT * FROM cart_items WHERE id=?',[req.params.id]);res.json(r[0])}))
app.delete('/api/cart/:id',route(async(req,res)=>{await q('DELETE FROM cart_items WHERE id=?',[req.params.id]);res.status(204).send()}))

app.get('/api/discounts',admin,route(async(_req,res)=>{const [r]=await q('SELECT * FROM discounts ORDER BY created_at DESC');res.json(r)}))
app.post('/api/discounts',admin,route(async(req,res)=>{const b=req.body||{},id=newId();await q('INSERT INTO discounts(id,code,description,discount,type,max_uses,active,expiry_date) VALUES(?,?,?,?,?,?,?,?)',[id,String(b.code||'').trim().toUpperCase(),String(b.description||''),Number(b.discount||0),String(b.type||'percent'),Number(b.maxUses||0),b.active===false?0:1,b.expiryDate||null]);const [r]=await q('SELECT * FROM discounts WHERE id=?',[id]);res.status(201).json(r[0])}))
app.patch('/api/discounts/:id',admin,route(async(req,res)=>{const b=req.body||{},sets=[],vals=[];const map={code:'code',description:'description',discount:'discount',type:'type',maxUses:'max_uses',active:'active',expiryDate:'expiry_date'};for(const k of Object.keys(map))if(b[k]!==undefined){sets.push(`${map[k]}=?`);vals.push(k==='code'?String(b[k]).toUpperCase():k==='active'?(b[k]?1:0):b[k])}if(!sets.length)return res.status(400).json({error:'No changes supplied'});vals.push(req.params.id);await q(`UPDATE discounts SET ${sets.join(',')} WHERE id=?`,vals);const [r]=await q('SELECT * FROM discounts WHERE id=?',[req.params.id]);res.json(r[0])}))
app.delete('/api/discounts/:id',admin,route(async(req,res)=>{await q('DELETE FROM discounts WHERE id=?',[req.params.id]);res.status(204).send()}))
app.post('/api/discounts/apply',route(async(req,res)=>{const [r]=await q(`SELECT * FROM discounts WHERE code=? AND active=1 AND (expiry_date IS NULL OR expiry_date>=CURDATE()) AND (max_uses=0 OR used_count<max_uses) LIMIT 1`,[String(req.body.code||'').trim().toUpperCase()]);if(!r[0])return res.status(404).json({error:'Discount not found or expired'});res.json(r[0])}))

app.get('/api/orders',admin,route(async(_req,res)=>{const [r]=await q('SELECT * FROM orders ORDER BY created_at DESC');for(const x of r){const [i]=await q('SELECT * FROM order_items WHERE order_id=?',[x.id]);x.items=i;x.total=Number(x.total);x.customerData=pj(x.customer_data);delete x.customer_data}res.json(r)}))
app.post('/api/orders',auth,route(async(req,res)=>{const items=Array.isArray(req.body.items)?req.body.items:[];if(!items.length)return res.status(400).json({error:'Order items are required'});const conn=await pool.getConnection(),orderId=uid();try{await conn.beginTransaction();let total=0,normalized=[];for(const item of items){const [r]=await conn.execute('SELECT id,name,price FROM products WHERE id=? AND active=1 LIMIT 1',[item.productId||item.id]);const p=r[0];if(!p)throw Object.assign(Error('Product not found'),{status:400});const qty=Math.max(1,Number(item.quantity||1)),price=Number(p.price);total+=price*qty;normalized.push([uid(),orderId,p.id,p.name,price,qty])}await conn.execute('INSERT INTO orders(id,user_id,username,total,status,payment_method,payment_ref,customer_data) VALUES(?,?,?,?,?,?,?,?)',[orderId,req.auth.sub,req.auth.username,total,String(req.body.status||'pending'),String(req.body.paymentMethod||''),String(req.body.paymentRef||''),j(req.body.customerData||{})]);for(const x of normalized)await conn.execute('INSERT INTO order_items(id,order_id,product_id,name,price,quantity) VALUES(?,?,?,?,?,?)',x);await conn.commit();res.status(201).json({id:orderId,userId:req.auth.sub,username:req.auth.username,total,status:req.body.status||'pending',items:normalized.map(x=>({id:x[0],productId:x[2],name:x[3],price:x[4],quantity:x[5]}))})}catch(e){await conn.rollback();throw e}finally{conn.release()}}))
app.patch('/api/orders/:id',admin,route(async(req,res)=>{const b=req.body||{},sets=[],vals=[];for(const [a,c] of [['status','status'],['paymentMethod','payment_method'],['paymentRef','payment_ref']])if(b[a]!==undefined){sets.push(`${c}=?`);vals.push(String(b[a]))}if(b.customerData!==undefined){sets.push('customer_data=?');vals.push(j(b.customerData))}if(!sets.length)return res.status(400).json({error:'No changes supplied'});vals.push(req.params.id);await q(`UPDATE orders SET ${sets.join(',')} WHERE id=?`,vals);const [r]=await q('SELECT * FROM orders WHERE id=?',[req.params.id]);res.json(r[0])}))

app.get('/api/tickets',admin,route(async(_req,res)=>{const [r]=await q('SELECT * FROM tickets ORDER BY created_at DESC');res.json(r.map(x=>({...x,replies:pa(x.replies)})))}))
app.post('/api/tickets',auth,route(async(req,res)=>{const id=newId();await q('INSERT INTO tickets(id,user_id,subject,message,status,priority,replies) VALUES(?,?,?,?,?,?,?)',[id,req.auth.sub,String(req.body.subject||''),String(req.body.message||''),'open',String(req.body.priority||'normal'),j([])]);const [r]=await q('SELECT * FROM tickets WHERE id=?',[id]);res.status(201).json(r[0])}))
app.patch('/api/tickets/:id',admin,route(async(req,res)=>{const b=req.body||{},sets=[],vals=[];for(const [a,c] of [['subject','subject'],['message','message'],['status','status'],['priority','priority']])if(b[a]!==undefined){sets.push(`${c}=?`);vals.push(String(b[a]))}if(b.replies!==undefined){sets.push('replies=?');vals.push(j(b.replies))}if(!sets.length)return res.status(400).json({error:'No changes supplied'});vals.push(req.params.id);await q(`UPDATE tickets SET ${sets.join(',')} WHERE id=?`,vals);const [r]=await q('SELECT * FROM tickets WHERE id=?',[req.params.id]);res.json(r[0])}))

app.get('/api/admin/overview',admin,route(async(_req,res)=>{const [[u]] = await q('SELECT COUNT(*) count FROM users'),[[p]]=await q('SELECT COUNT(*) count FROM products'),[[b]]=await q('SELECT COUNT(*) count FROM blog_posts'),[[o]]=await q('SELECT COUNT(*) count FROM orders'),[[t]]=await q("SELECT COUNT(*) count FROM tickets WHERE status IN ('open','pending')"),[[v]]=await q("SELECT COALESCE(SUM(total),0) total FROM orders WHERE status IN ('paid','completed','success')"),[s]=await q('SELECT * FROM server_stats WHERE id=1');res.json({users:Number(u.count),products:Number(p.count),posts:Number(b.count),orders:Number(o.count),openTickets:Number(t.count),revenue:Number(v.total||0),serverStats:s[0]||{}})}))
app.get('/api/admin/data/:table',admin,route(async(req,res)=>{const m={users:'users',products:'products',blog:'blog_posts',orders:'orders',tickets:'tickets',discounts:'discounts',transactions:'transactions',notifications:'notifications',cart:'cart_items'},table=m[req.params.table];if(!table)return res.status(400).json({error:'Table is not allowed'});const [r]=await q(`SELECT * FROM ${table} LIMIT 1000`);res.json(r)}))
app.post('/api/pay-with-wallet',auth,route(async(req,res)=>{const amount=Math.max(0,Number(req.body.amount||0));if(!amount)return res.status(400).json({error:'Amount must be positive'});const c=await pool.getConnection();try{await c.beginTransaction();const [r]=await c.execute('SELECT wallet FROM users WHERE id=? FOR UPDATE',[req.auth.sub]);const wallet=Number(r[0]?.wallet||0);if(wallet<amount){await c.rollback();return res.status(400).json({error:'Insufficient wallet balance'})}const id=newId();await c.execute('UPDATE users SET wallet=wallet-? WHERE id=?',[amount,req.auth.sub]);await c.execute('INSERT INTO transactions(id,user_id,amount,type,status,reference_code) VALUES(?,?,?,?,?,?)',[id,req.auth.sub,amount,'wallet_payment','completed',String(req.body.reference||'')]);await c.commit();res.json({success:true,transactionId:id,amount,balance:wallet-amount})}catch(e){await c.rollback();throw e}finally{c.release()}}))
app.post('/api/create-bale-invoice',auth,route(async(req,res)=>{const url=String(process.env.BALE_PAYMENT_URL||'').trim();if(!url)return res.status(503).json({error:'Bale payment is not configured'});res.json({success:true,paymentUrl:url,amount:Number(req.body.amount||0)})}))
app.post('/api/bale-callback',route(async(_req,res)=>res.json({ok:true,received:true})))
app.use((req,res)=>res.status(404).json({error:'Route not found',path:req.path,prefix:PREFIX}))
app.use((err,_req,res,_next)=>{console.error(err);res.status(Number(err.status)||500).json({error:process.env.NODE_ENV==='production'?'Internal server error':err.message||'Internal server error'})})
async function start(){await schema();await q('SELECT 1');app.listen(PORT,()=>console.log(`BinerCraft backend listening on ${PORT} (${PREFIX})`))}
start().catch(e=>{console.error('BinerCraft backend failed:',e);process.exit(1)})
const stop=async()=>{try{await pool.end()}finally{process.exit(0)}}
process.on('SIGTERM',stop);process.on('SIGINT',stop)
