const express = require('express')
const cors = require('cors')
const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

const app = express()
const PORT = Number(process.env.PORT) || 3000
const DB_PATH = path.join(__dirname, 'db.json')
const DEFAULT_DB = { users: [], products: [], blog: [], orders: [], cart: [], notifications: [], discounts: [], tickets: [], transactions: [], siteSettings: { siteName: 'BinerCraft', supportEmail: 'support@binercraft.ir', supportHours: 'هر روز، ۹ تا ۲۳', contactText: 'تیم BinerCraft آماده پاسخ‌گویی به شماست.', serverAddress: 'play.binercraft.ir', announcement: '' }, serverStats: { players: 0, stability: 99.9, sales: 0, support: 0, status: 'online' } }
const allowedOrigins = ['http://localhost:5173', 'http://127.0.0.1:5173', ...(process.env.FRONTEND_URL || '').split(',').map((v) => v.trim()).filter(Boolean)]
const configuredBaleToken = process.env.BALE_WALLET_TOKEN && !process.env.BALE_WALLET_TOKEN.startsWith('YOUR_') ? process.env.BALE_WALLET_TOKEN : ''
const configuredBalePaymentUrl = process.env.BALE_PAYMENT_URL && !process.env.BALE_PAYMENT_URL.startsWith('YOUR_') ? process.env.BALE_PAYMENT_URL : ''
const ADMIN_USERNAME = String(process.env.ADMIN_USERNAME || 'hirad990').trim().toLowerCase()
const ADMIN_PASSWORD = String(process.env.ADMIN_PASSWORD || '')
const AUTH_SECRET = String(process.env.AUTH_SECRET || '').trim()
if (!AUTH_SECRET) console.warn('AUTH_SECRET is not configured.')
if (!ADMIN_PASSWORD) console.warn('ADMIN_PASSWORD is not configured. Admin login is disabled.')
app.use(cors({ origin(origin, cb) { if (!origin || allowedOrigins.includes(origin) || /^https?:\/\/localhost(?::\d+)?$/.test(origin) || /^https?:\/\/127\.0\.0\.1(?::\d+)?$/.test(origin)) return cb(null, true); return cb(new Error('CORS origin is not allowed')) } }))
app.use(express.json({ limit: '1mb' }))
function ensureDBShape(db) { const result = { ...DEFAULT_DB, ...(db && typeof db === 'object' ? db : {}) }; for (const k of ['users','products','blog','orders','cart','notifications','discounts','tickets','transactions']) if (!Array.isArray(result[k])) result[k] = []; result.siteSettings = { ...DEFAULT_DB.siteSettings, ...(result.siteSettings || {}) }; result.serverStats = { ...DEFAULT_DB.serverStats, ...(result.serverStats || {}) }; return result }
function readDB() { try { if (!fs.existsSync(DB_PATH)) { const db = ensureDBShape(DEFAULT_DB); writeDB(db); return db } return ensureDBShape(JSON.parse(fs.readFileSync(DB_PATH, 'utf8').replace(/^\uFEFF/, ''))) } catch (e) { console.error('Error reading database:', e.message); return ensureDBShape(DEFAULT_DB) } }
function writeDB(data) { try { const tmp = `${DB_PATH}.tmp`; fs.writeFileSync(tmp, `${JSON.stringify(ensureDBShape(data), null, 2)}\n`, 'utf8'); fs.renameSync(tmp, DB_PATH); return true } catch (e) { console.error('Error writing database:', e.message); return false } }
function generateId() { return `${Date.now().toString(36)}-${crypto.randomBytes(5).toString('hex')}` }
function hashPassword(password) { const salt = crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}` }
function verifyPassword(password, stored) { if (!stored || !stored.includes(':')) return false; const [salt, hash] = stored.split(':'); try { return crypto.timingSafeEqual(Buffer.from(hash, 'hex'), Buffer.from(crypto.scryptSync(password, salt, 64).toString('hex'), 'hex')) } catch { return false } }
function sanitizeUser(user) { if (!user) return null; const { password, passwordHash, ...safe } = user; return safe }
function signToken(payload) { const h = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url'); const b = Buffer.from(JSON.stringify(payload)).toString('base64url'); const s = crypto.createHmac('sha256', AUTH_SECRET || 'development-only-secret').update(`${h}.${b}`).digest('base64url'); return `${h}.${b}.${s}` }
function verifyToken(token) { if (!token || !AUTH_SECRET) return null; const p = token.split('.'); if (p.length !== 3) return null; const expected = crypto.createHmac('sha256', AUTH_SECRET).update(`${p[0]}.${p[1]}`).digest('base64url'); if (p[2].length !== expected.length || !crypto.timingSafeEqual(Buffer.from(p[2]), Buffer.from(expected))) return null; try { const payload = JSON.parse(Buffer.from(p[1], 'base64url').toString('utf8')); return payload.exp && payload.exp >= Math.floor(Date.now() / 1000) ? payload : null } catch { return null } }
function requireAuth(req, res, next) { const h = String(req.headers.authorization || ''); const user = verifyToken(h.startsWith('Bearer ') ? h.slice(7).trim() : ''); if (!user) return res.status(401).json({ error: 'Authentication required' }); req.auth = user; next() }
function requireAdmin(req, res, next) { return requireAuth(req, res, () => req.auth.role === 'admin' ? next() : res.status(403).json({ error: 'Admin access required' })) }
function save(res, db, payload, code = 200) { if (!writeDB(db)) return res.status(500).json({ error: 'Could not save data' }); return res.status(code).json(payload) }

app.get('/api/health', (req, res) => res.json({ status: 'ok', service: 'BinerCraft Backend', timestamp: new Date().toISOString() }))
app.post('/api/auth/admin/login', (req, res) => { if (!ADMIN_PASSWORD || !AUTH_SECRET) return res.status(503).json({ error: 'Admin authentication is not configured' }); const username = String(req.body.username || req.body.identifier || '').trim().toLowerCase(); if (username !== ADMIN_USERNAME || String(req.body.password || '') !== ADMIN_PASSWORD) return res.status(401).json({ error: 'Invalid admin credentials' }); const db = readDB(); let admin = db.users.find((u) => u.role === 'admin' && String(u.username || '').toLowerCase() === ADMIN_USERNAME); if (!admin) { admin = { id: generateId(), username: ADMIN_USERNAME, email: `${ADMIN_USERNAME}@binercraft.ir`, displayName: 'مدیر BinerCraft', role: 'admin', wallet: 0, avatar: '' }; db.users.push(admin); writeDB(db) } const token = signToken({ sub: String(admin.id), username: admin.username, role: 'admin', exp: Math.floor(Date.now() / 1000) + 43200 }); res.json({ token, user: sanitizeUser(admin) }) })
app.post('/api/users/register', (req, res) => { const db = readDB(); const username = String(req.body.username || '').trim(); const email = String(req.body.email || '').trim().toLowerCase(); const password = String(req.body.password || ''); const displayName = String(req.body.displayName || username).trim(); if (username.length < 3 || !/^[-_a-zA-Z0-9]+$/.test(username)) return res.status(400).json({ error: 'Invalid username' }); if (!/^\S+@\S+\.\S+$/.test(email)) return res.status(400).json({ error: 'Invalid email' }); if (password.length < 8) return res.status(400).json({ error: 'Password must contain at least 8 characters' }); if (db.users.some((u) => u.username?.toLowerCase() === username.toLowerCase())) return res.status(409).json({ error: 'Username already exists' }); if (db.users.some((u) => u.email?.toLowerCase() === email)) return res.status(409).json({ error: 'Email already exists' }); const user = { id: generateId(), username, email, displayName: displayName || username, role: 'user', wallet: 0, avatar: '', passwordHash: hashPassword(password), createdAt: new Date().toISOString() }; db.users.push(user); return save(res, db, sanitizeUser(user), 201) })
app.post('/api/users/login', (req, res) => { const db = readDB(); const identifier = String(req.body.identifier || req.body.username || req.body.email || '').trim().toLowerCase(); const user = db.users.find((u) => u.username?.toLowerCase() === identifier || u.email?.toLowerCase() === identifier); if (!user || !verifyPassword(String(req.body.password || ''), user.passwordHash)) return res.status(401).json({ error: 'Invalid username/email or password' }); const token = AUTH_SECRET ? signToken({ sub: String(user.id), username: user.username, role: user.role || 'user', exp: Math.floor(Date.now() / 1000) + 43200 }) : null; res.json({ user: sanitizeUser(user), ...(token ? { token } : {}) }) })
app.get('/api/auth/me', requireAuth, (req, res) => { const user = readDB().users.find((u) => String(u.id) === String(req.auth.sub)); return user ? res.json({ user: sanitizeUser(user) }) : res.status(401).json({ error: 'User not found' }) })

app.get('/api/users', requireAdmin, (req, res) => res.json(readDB().users.map(sanitizeUser)))
app.post('/api/users', requireAdmin, (req, res) => { const db = readDB(); const user = { id: generateId(), username: String(req.body.username || '').trim(), email: String(req.body.email || '').trim().toLowerCase(), displayName: String(req.body.displayName || req.body.username || '').trim(), role: req.body.role === 'admin' ? 'admin' : 'user', wallet: Number(req.body.wallet || 0), avatar: String(req.body.avatar || ''), ...(req.body.password ? { passwordHash: hashPassword(String(req.body.password)) } : {}) }; if (!user.username || db.users.some((u) => u.username.toLowerCase() === user.username.toLowerCase())) return res.status(400).json({ error: 'Invalid or duplicate username' }); db.users.push(user); return save(res, db, sanitizeUser(user), 201) })
app.patch('/api/users/:id', requireAdmin, (req, res) => { const db = readDB(); const i = db.users.findIndex((u) => String(u.id) === String(req.params.id)); if (i < 0) return res.status(404).json({ error: 'User not found' }); const updates = { ...req.body }; if (updates.password) { updates.passwordHash = hashPassword(String(updates.password)); delete updates.password } if (updates.role && !['user','admin'].includes(updates.role)) return res.status(400).json({ error: 'Invalid role' }); db.users[i] = { ...db.users[i], ...updates }; return save(res, db, sanitizeUser(db.users[i])) })
app.delete('/api/users/:id', requireAdmin, (req, res) => { if (String(req.params.id) === String(req.auth.sub)) return res.status(400).json({ error: 'You cannot delete your own account' }); const db = readDB(); db.users = db.users.filter((u) => String(u.id) !== String(req.params.id)); writeDB(db); res.status(204).send() })

app.get('/api/products', (req, res) => res.json(readDB().products))
app.post('/api/products', requireAdmin, (req, res) => { const db = readDB(); const item = { id: generateId(), ...req.body, name: String(req.body.name || ''), price: Number(req.body.price || 0) }; db.products.push(item); return save(res, db, item, 201) })
app.patch('/api/products/:id', requireAdmin, (req, res) => { const db = readDB(); const i = db.products.findIndex((p) => String(p.id) === String(req.params.id)); if (i < 0) return res.status(404).json({ error: 'Product not found' }); db.products[i] = { ...db.products[i], ...req.body, ...(req.body.price !== undefined ? { price: Number(req.body.price) } : {}) }; return save(res, db, db.products[i]) })
app.delete('/api/products/:id', requireAdmin, (req, res) => { const db = readDB(); db.products = db.products.filter((p) => String(p.id) !== String(req.params.id)); writeDB(db); res.status(204).send() })

app.get('/api/blog', (req, res) => res.json(readDB().blog))
app.post('/api/blog', requireAdmin, (req, res) => { const db = readDB(); const post = { id: generateId(), title: String(req.body.title || ''), summary: String(req.body.summary || ''), content: String(req.body.content || ''), author: String(req.body.author || 'تیم BinerCraft'), authorId: String(req.auth.sub), date: new Date().toISOString().slice(0,10), likes: 0, comments: [], category: String(req.body.category || 'اخبار'), image: String(req.body.image || ''), published: req.body.published !== false }; db.blog.push(post); return save(res, db, post, 201) })
app.patch('/api/blog/:id', requireAdmin, (req, res) => { const db = readDB(); const i = db.blog.findIndex((p) => String(p.id) === String(req.params.id)); if (i < 0) return res.status(404).json({ error: 'Post not found' }); db.blog[i] = { ...db.blog[i], ...req.body }; return save(res, db, db.blog[i]) })
app.delete('/api/blog/:id', requireAdmin, (req, res) => { const db = readDB(); db.blog = db.blog.filter((p) => String(p.id) !== String(req.params.id)); writeDB(db); res.status(204).send() })

app.get('/api/site-settings', (req, res) => res.json(readDB().siteSettings))
app.patch('/api/site-settings', requireAdmin, (req, res) => { const db = readDB(); db.siteSettings = { ...db.siteSettings, ...req.body }; return save(res, db, db.siteSettings) })
app.get('/api/server-stats', (req, res) => res.json(readDB().serverStats))
app.patch('/api/server-stats', requireAdmin, (req, res) => { const db = readDB(); db.serverStats = { ...db.serverStats, ...req.body }; return save(res, db, db.serverStats) })
app.get('/api/admin/overview', requireAdmin, (req, res) => { const db = readDB(); const revenue = db.orders.reduce((sum, o) => sum + Number(o.total || o.amount || 0), 0); res.json({ users: db.users.length, admins: db.users.filter((u) => u.role === 'admin').length, products: db.products.length, posts: db.blog.length, orders: db.orders.length, pendingOrders: db.orders.filter((o) => ['pending','processing'].includes(o.status)).length, openTickets: db.tickets.filter((t) => !['closed','resolved'].includes(t.status)).length, discounts: db.discounts.length, notifications: db.notifications.length, revenue, serverStats: db.serverStats }) })

app.get('/api/orders', requireAuth, (req, res) => { const db = readDB(); if (req.auth.role === 'admin') return res.json(req.query.userId ? db.orders.filter((o) => String(o.userId) === String(req.query.userId)) : db.orders); return res.json(db.orders.filter((o) => String(o.userId) === String(req.auth.sub))) })
app.post('/api/orders', requireAuth, (req, res) => { const db = readDB(); const order = { id: generateId(), ...req.body, userId: String(req.auth.sub), createdAt: new Date().toISOString(), status: req.body.status || 'pending' }; db.orders.push(order); return save(res, db, order, 201) })

function cartFor(db, userId) { return db.cart.filter((i) => String(i.userId || 'guest') === String(userId)).map((i) => ({ ...i, product: db.products.find((p) => String(p.id) === String(i.productId)) || null })) }
app.get('/api/cart', (req, res) => res.json(cartFor(readDB(), String(req.query.userId || 'guest'))))
app.post('/api/cart', (req, res) => { const db = readDB(); const userId = String(req.body.userId || 'guest'); const productId = String(req.body.productId || ''); if (!db.products.some((p) => String(p.id) === productId)) return res.status(404).json({ error: 'Product not found' }); const q = Math.max(1, Number(req.body.quantity || 1)); const old = db.cart.find((i) => String(i.userId || 'guest') === userId && String(i.productId) === productId); if (old) old.quantity += q; else db.cart.push({ id: generateId(), userId, productId, quantity: q }); writeDB(db); res.json(cartFor(db, userId)) })
app.patch('/api/cart/:id', (req, res) => { const db = readDB(); const userId = String(req.body.userId || req.query.userId || 'guest'); const item = db.cart.find((i) => String(i.id) === String(req.params.id) && String(i.userId || 'guest') === userId); if (!item) return res.status(404).json({ error: 'Cart item not found' }); item.quantity = Math.max(1, Number(req.body.quantity || 1)); writeDB(db); res.json(cartFor(db, userId)) })
app.delete('/api/cart/:id', (req, res) => { const db = readDB(); const userId = String(req.body.userId || req.query.userId || 'guest'); db.cart = db.cart.filter((i) => !(String(i.id) === String(req.params.id) && String(i.userId || 'guest') === userId)); writeDB(db); res.json(cartFor(db, userId)) })
app.delete('/api/cart', (req, res) => { const db = readDB(); const userId = String(req.body.userId || req.query.userId || 'guest'); db.cart = db.cart.filter((i) => String(i.userId || 'guest') !== userId); writeDB(db); res.json(cartFor(db, userId)) })

app.get('/api/notifications', requireAuth, (req, res) => { const db = readDB(); res.json(db.notifications.filter((n) => !n.targetUserId || String(n.targetUserId) === String(req.auth.sub))) })
app.post('/api/notifications', requireAdmin, (req, res) => { const db = readDB(); const n = { id: generateId(), ...req.body, read: false, createdAt: new Date().toISOString() }; db.notifications.push(n); return save(res, db, n, 201) })
app.patch('/api/notifications/:id', requireAuth, (req, res) => { const db = readDB(); const i = db.notifications.findIndex((n) => String(n.id) === String(req.params.id) && (req.auth.role === 'admin' || !n.targetUserId || String(n.targetUserId) === String(req.auth.sub))); if (i < 0) return res.status(404).json({ error: 'Notification not found' }); db.notifications[i] = { ...db.notifications[i], ...req.body }; return save(res, db, db.notifications[i]) })
app.delete('/api/notifications/:id', requireAdmin, (req, res) => { const db = readDB(); db.notifications = db.notifications.filter((n) => String(n.id) !== String(req.params.id)); writeDB(db); res.status(204).send() })

app.get('/api/discounts', (req, res) => res.json(readDB().discounts))
app.post('/api/discounts', requireAdmin, (req, res) => { const db = readDB(); const d = { id: generateId(), ...req.body, code: String(req.body.code || '').toUpperCase() }; db.discounts.push(d); return save(res, db, d, 201) })
app.patch('/api/discounts/:id', requireAdmin, (req, res) => { const db = readDB(); const i = db.discounts.findIndex((d) => String(d.id) === String(req.params.id)); if (i < 0) return res.status(404).json({ error: 'Discount not found' }); db.discounts[i] = { ...db.discounts[i], ...req.body }; return save(res, db, db.discounts[i]) })
app.delete('/api/discounts/:id', requireAdmin, (req, res) => { const db = readDB(); db.discounts = db.discounts.filter((d) => String(d.id) !== String(req.params.id)); writeDB(db); res.status(204).send() })
app.post('/api/discounts/apply', (req, res) => { const db = readDB(); const code = String(req.body.code || '').trim().toUpperCase(); const d = db.discounts.find((x) => String(x.code || '').toUpperCase() === code && x.active !== false); if (!d) return res.status(404).json({ error: 'Discount code is invalid or inactive' }); if (d.expiryDate && new Date(d.expiryDate) < new Date()) return res.status(400).json({ error: 'Discount code has expired' }); const amount = Math.max(0, Number(req.body.amount || 0)); const discountAmount = d.type === 'fixed' ? Math.min(amount, Number(d.discount || 0)) : amount * Number(d.discount || 0) / 100; res.json({ code: d.code, discount: Number(d.discount || 0), type: d.type || 'percent', discountAmount, finalAmount: Math.max(0, amount - discountAmount) }) })

app.get('/api/tickets', requireAuth, (req, res) => { const db = readDB(); res.json(req.auth.role === 'admin' ? db.tickets : db.tickets.filter((t) => String(t.userId) === String(req.auth.sub))) })
app.post('/api/tickets', requireAuth, (req, res) => { const db = readDB(); const t = { id: generateId(), ...req.body, userId: String(req.auth.sub), status: 'open', createdAt: new Date().toISOString() }; db.tickets.push(t); return save(res, db, t, 201) })
app.patch('/api/tickets/:id', requireAuth, (req, res) => { const db = readDB(); const i = db.tickets.findIndex((t) => String(t.id) === String(req.params.id) && (req.auth.role === 'admin' || String(t.userId) === String(req.auth.sub))); if (i < 0) return res.status(404).json({ error: 'Ticket not found' }); db.tickets[i] = { ...db.tickets[i], ...req.body }; return save(res, db, db.tickets[i]) })
app.delete('/api/tickets/:id', requireAdmin, (req, res) => { const db = readDB(); db.tickets = db.tickets.filter((t) => String(t.id) !== String(req.params.id)); writeDB(db); res.status(204).send() })

app.get('/api/wallet/:userId', requireAuth, (req, res) => { if (req.auth.role !== 'admin' && String(req.auth.sub) !== String(req.params.userId)) return res.status(403).json({ error: 'Forbidden' }); const user = readDB().users.find((u) => String(u.id) === String(req.params.userId)); if (!user) return res.status(404).json({ error: 'User not found' }); res.json({ wallet: Number(user.wallet || 0) }) })
app.post('/api/pay-with-wallet', requireAuth, (req, res) => { const db = readDB(); const user = db.users.find((u) => String(u.id) === String(req.auth.sub)); const amount = Number(req.body.amount); if (!user || !Number.isFinite(amount) || amount <= 0) return res.status(400).json({ error: 'Invalid payment' }); if (Number(user.wallet || 0) < amount) return res.status(400).json({ error: 'Insufficient wallet balance' }); user.wallet -= amount; db.transactions.push({ id: generateId(), userId: user.id, amount: -amount, type: 'wallet-payment', createdAt: new Date().toISOString() }); writeDB(db); res.json({ success: true, newBalance: user.wallet }) })
app.post('/api/create-bale-invoice', requireAuth, (req, res) => { const amount = Number(req.body.amount); if (!Number.isFinite(amount) || amount <= 0) return res.status(400).json({ error: 'Invalid amount' }); res.json({ success: true, paymentUrl: configuredBalePaymentUrl || null, invoiceId: generateId(), amount, description: String(req.body.description || 'خرید از BinerCraft'), status: 'pending', configured: Boolean(configuredBaleToken && configuredBalePaymentUrl) }) })
app.post('/api/bale-callback', (req, res) => { if (!req.body.invoiceId) return res.status(400).json({ success: false, message: 'invoiceId is required' }); res.json(req.body.status === 'paid' ? { success: true, message: 'Payment confirmed', transactionId: req.body.transactionId || null } : { success: false, message: 'Payment failed or cancelled' }) })

app.use((req, res) => res.status(404).json({ error: 'Route not found' }))
app.use((error, req, res, next) => { console.error(error); if (res.headersSent) return next(error); res.status(500).json({ error: 'Internal server error' }) })
app.listen(PORT, () => console.log(`BinerCraft Backend running on http://localhost:${PORT}`))
